// The real generator registry `pnpm check:generated` runs (TASKS.md 2.2.g,
// 3.5.b). Every file below is one nobody hand-edits (PARALLEL-TRACKS.md §2); each
// is regenerated by the CMS package's own script with `BRAND` unset and once per
// brand context (`contexts.mjs`), none of them given a DATABASE_URL:
//
//   migration-snapshot     `schema:check` (BRAND unset): the config against the
//                          latest committed snapshot in cms/src/migrations — a
//                          collection changed without the wave's migration fails
//   migration-snapshot [B] `schema:check print` under each brand B, equal to its
//                          output with BRAND unset — a config shaped by BRAND
//                          would give two brands two schemas (ARCHITECTURE.md §2)
//   payload-types [B]      `generate:types` under every context, equal to the one
//                          committed engine/packages/cms/payload-types.ts
//   importmap.<app> [B]    `generate:importmap <app>` under every context, equal
//                          to the app's committed importMap.js — for each app
//                          that mounts the admin; skipped with a notice until one
//                          does (TASKS.md 4.1.a)
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

import { cmsScripts, limiter, PAYLOAD_TYPES } from './cms-scripts.mjs'
import { NothingToCheckYet } from './config-drift.mjs'
import { brandContexts } from './contexts.mjs'

export const MIGRATIONS = 'engine/packages/cms/src/migrations'
/** Where an app mounts Payload's admin, and its import map (the CMS script's own ADMIN_PATH). */
export const ADMIN_PATH = 'src/app/(payload)/admin'
const importMapPath = (app) => `engine/apps/${app}/${ADMIN_PATH}/importMap.js`

/** Every app under engine/apps/ with an admin mount, sorted. */
export function appsWithAdminMount(repoRoot) {
  const appsDir = join(repoRoot, 'engine', 'apps')
  if (!existsSync(appsDir)) return []
  return readdirSync(appsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((app) => existsSync(join(appsDir, app, ...ADMIN_PATH.split('/'))))
    .sort()
}

function readOrNull(file) {
  try {
    return readFileSync(file, 'utf8')
  } catch {
    return null
  }
}

/**
 * The generators for `repoRoot`. `scripts` and `contexts` are injectable so a
 * test can stand fixture scripts in for Payload; CI uses the defaults.
 */
export function realGenerators(
  repoRoot,
  { scripts = cmsScripts(repoRoot), contexts = brandContexts(repoRoot) } = {},
) {
  const [unset, ...brands] = contexts
  const generators = [
    {
      name: 'migration-snapshot',
      committedPath: MIGRATIONS,
      check: () => scripts.schemaCheck(unset),
    },
    ...brands.map((context) => ({
      name: `migration-snapshot [${context.label}]`,
      committedPath: MIGRATIONS,
      regenerate: () => scripts.snapshot(context),
      expected: () => scripts.snapshot(unset),
    })),
    ...contexts.map((context) => ({
      name: `payload-types [${context.label}]`,
      committedPath: PAYLOAD_TYPES,
      required: true,
      regenerate: () => scripts.payloadTypes(context),
    })),
  ]

  const apps = appsWithAdminMount(repoRoot)
  if (apps.length === 0) {
    generators.push({
      name: 'importmap',
      committedPath: importMapPath('<app>'),
      regenerate: () => {
        throw new NothingToCheckYet(
          `no app under engine/apps/* mounts the admin at ${ADMIN_PATH} (TASKS.md 4.1.a), so generate:importmap is skipped — it would exit 1 with "no admin mount"`,
        )
      },
    })
  }
  for (const app of apps) {
    const committedPath = importMapPath(app)
    const committedAbs = join(repoRoot, ...committedPath.split('/'))
    // Read once, before any run: the script rewrites this file while it runs.
    const committed = readOrNull(committedAbs)
    const oneAtATime = limiter(1)
    for (const context of contexts) {
      generators.push({
        name: `importmap.${app} [${context.label}]`,
        committedPath,
        required: true,
        referenceName: 'committed',
        regenerate: () => oneAtATime(() => scripts.importMap(context, app, committedAbs)),
        expected: () => committed,
      })
    }
  }
  return generators
}
