// The real generator registry `pnpm check:generated` runs (TASKS.md 1.3.c). Every file below is
// one nobody hand-edits (AGENTS.md); each is regenerated by the CMS package's own script in one
// environment with no DATABASE_URL (`contexts.mjs`) and compared with the committed file:
//
//   payload-types      `generate:types`, equal to the committed engine/packages/cms/payload-types.ts
//   importmap.<app>    `generate:importmap <app>`, equal to the app's committed importMap.js — for
//                      each app that mounts the admin; a component missing from the map renders as
//                      nothing, with no error (CARRY-OVER.md §4)
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

import { cmsScripts, PAYLOAD_TYPES } from './cms-scripts.mjs'
import { NothingToCheckYet } from './config-drift.mjs'

/** Where an app mounts Payload's admin, and its import map (the CMS script's own ADMIN_PATH). */
export const ADMIN_PATH = 'src/app/(payload)/admin'
const importMapPath = (app) => `engine/apps/${app}/${ADMIN_PATH}/importMap.js`

/** Every app under engine/apps/ with an admin mount, sorted. */
export function appsWithAdminMount(repoRoot) {
  const appsDir = join(repoRoot, 'engine', 'apps')
  if (!existsSync(appsDir)) return []
  return readdirSync(appsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((app) => existsSync(join(appsDir, app, ...ADMIN_PATH.split('/'))))
    .sort()
}

function readOrNull(file) {
  try {
    return readFileSync(file, 'utf8')
  } catch {
    return null
  }
}

/** The generators for `repoRoot`. `scripts` is injectable so a test can stand in for Payload. */
export function realGenerators(repoRoot, { scripts = cmsScripts(repoRoot) } = {}) {
  const generators = [
    {
      name: 'payload-types',
      committedPath: PAYLOAD_TYPES,
      required: true,
      regenerate: () => scripts.payloadTypes(),
    },
  ]

  const apps = appsWithAdminMount(repoRoot)
  if (apps.length === 0) {
    generators.push({
      name: 'importmap',
      committedPath: importMapPath('<app>'),
      regenerate: () => {
        throw new NothingToCheckYet(
          `no app under engine/apps/* mounts the admin at ${ADMIN_PATH}, so generate:importmap is skipped — it would exit 1 with "no admin mount"`,
        )
      },
    })
  }
  for (const app of apps) {
    const committedPath = importMapPath(app)
    const committedAbs = join(repoRoot, ...committedPath.split('/'))
    // Read before the run: the script rewrites this file while it runs (and puts it back).
    const committed = readOrNull(committedAbs)
    generators.push({
      name: `importmap.${app}`,
      committedPath,
      required: true,
      regenerate: () => scripts.importMap(app, committedAbs),
      expected: () => committed,
    })
  }
  return generators
}
