/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    customers: Customer
    addresses: Address
    'saved-items': SavedItem
    'want-lists': WantList
    subscribers: Subscriber
    reviews: Review
    makers: Maker
    places: Place
    terms: Term
    sources: Source
    curations: Curation
    works: Work
    designs: Design
    products: Product
    'product-types': ProductType
    variants: Variant
    locations: Location
    'stock-levels': StockLevel
    media: Media
    masters: Master
    stories: Story
    pages: Page
    exhibitions: Exhibition
    redirects: Redirect
    carts: Cart
    reservations: Reservation
    orders: Order
    'payment-attempts': PaymentAttempt
    refunds: Refund
    shipments: Shipment
    returns: Return
    offers: Offer
    enquiries: Enquiry
    consignments: Consignment
    appointments: Appointment
    invoices: Invoice
    discounts: Discount
    'gift-cards': GiftCard
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {
    places: {
      children: 'places'
    }
  }
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    customers: CustomersSelect<false> | CustomersSelect<true>
    addresses: AddressesSelect<false> | AddressesSelect<true>
    'saved-items': SavedItemsSelect<false> | SavedItemsSelect<true>
    'want-lists': WantListsSelect<false> | WantListsSelect<true>
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>
    reviews: ReviewsSelect<false> | ReviewsSelect<true>
    makers: MakersSelect<false> | MakersSelect<true>
    places: PlacesSelect<false> | PlacesSelect<true>
    terms: TermsSelect<false> | TermsSelect<true>
    sources: SourcesSelect<false> | SourcesSelect<true>
    curations: CurationsSelect<false> | CurationsSelect<true>
    works: WorksSelect<false> | WorksSelect<true>
    designs: DesignsSelect<false> | DesignsSelect<true>
    products: ProductsSelect<false> | ProductsSelect<true>
    'product-types': ProductTypesSelect<false> | ProductTypesSelect<true>
    variants: VariantsSelect<false> | VariantsSelect<true>
    locations: LocationsSelect<false> | LocationsSelect<true>
    'stock-levels': StockLevelsSelect<false> | StockLevelsSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    masters: MastersSelect<false> | MastersSelect<true>
    stories: StoriesSelect<false> | StoriesSelect<true>
    pages: PagesSelect<false> | PagesSelect<true>
    exhibitions: ExhibitionsSelect<false> | ExhibitionsSelect<true>
    redirects: RedirectsSelect<false> | RedirectsSelect<true>
    carts: CartsSelect<false> | CartsSelect<true>
    reservations: ReservationsSelect<false> | ReservationsSelect<true>
    orders: OrdersSelect<false> | OrdersSelect<true>
    'payment-attempts': PaymentAttemptsSelect<false> | PaymentAttemptsSelect<true>
    refunds: RefundsSelect<false> | RefundsSelect<true>
    shipments: ShipmentsSelect<false> | ShipmentsSelect<true>
    returns: ReturnsSelect<false> | ReturnsSelect<true>
    offers: OffersSelect<false> | OffersSelect<true>
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>
    consignments: ConsignmentsSelect<false> | ConsignmentsSelect<true>
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>
    invoices: InvoicesSelect<false> | InvoicesSelect<true>
    discounts: DiscountsSelect<false> | DiscountsSelect<true>
    'gift-cards': GiftCardsSelect<false> | GiftCardsSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('en' | 'id' | 'nl') | ('en' | 'id' | 'nl')[]
  globals: {
    'brand-settings': BrandSetting
    navigation: Navigation
    homepage: Homepage
    'commerce-settings': CommerceSetting
    consent: Consent
    'seo-defaults': SeoDefault
  }
  globalsSelect: {
    'brand-settings': BrandSettingsSelect<false> | BrandSettingsSelect<true>
    navigation: NavigationSelect<false> | NavigationSelect<true>
    homepage: HomepageSelect<false> | HomepageSelect<true>
    'commerce-settings': CommerceSettingsSelect<false> | CommerceSettingsSelect<true>
    consent: ConsentSelect<false> | ConsentSelect<true>
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>
  }
  locale: 'en' | 'id' | 'nl'
  widgets: {
    collections: CollectionsWidget
  }
  strictDraftTypes: true
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * Who can sign in to this admin, and what each person may do.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  /**
   * As colleagues know you — shown on the records you change.
   */
  name: string
  /**
   * Admin: everything, including staff and settings. Manager: catalogue, prices, orders, refunds. Cataloguer: works, makers, places, media — no prices or orders. Editor: stories, pages, curations; publishes. Fulfilment: orders, shipments, returns. Analyst: read-only and dashboards. Contributor: drafts only.
   */
  roles: (
    'admin' | 'manager' | 'cataloguer' | 'editor' | 'fulfilment' | 'analyst' | 'contributor'
  )[]
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  resetPasswordRequestedAt?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-items".
 */
export interface SavedItem {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "want-lists".
 */
export interface WantList {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makers".
 */
export interface Maker {
  id: number
  /**
   * As the maker is known: "François Valentijn", "Woodbury & Page".
   */
  name: string
  /**
   * As a collector’s maker line reads, surname first: "BLAEU, Willem Janszoon".
   */
  sortName: string
  /**
   * The address of its page. Made once from the name; renaming the record never changes it, so links keep working.
   */
  slug: string
  /**
   * Valentyn beside Valentijn: the spellings a search should also find.
   */
  aliases?:
    | {
        name: string
        id?: string | null
      }[]
    | null
  /**
   * What the maker is known for. A work names the role on that work.
   */
  roles?:
    | (
        | 'cartographer'
        | 'engraver'
        | 'publisher'
        | 'author'
        | 'artist'
        | 'photographer'
        | 'studio'
        | 'printer'
      )[]
    | null
  born: {
    precision: 'exact' | 'circa' | 'before' | 'after' | 'range' | 'unknown'
    from?: number | null
    to?: number | null
    /**
     * Your own wording, if the year alone says it wrong: "1724–26".
     */
    display?: string | null
  }
  died: {
    precision: 'exact' | 'circa' | 'before' | 'after' | 'range' | 'unknown'
    from?: number | null
    to?: number | null
    /**
     * Your own wording, if the year alone says it wrong: "1724–26".
     */
    display?: string | null
  }
  /**
   * "Dutch", "Belanda" — in each language.
   */
  nationality?: string | null
  /**
   * A portrait, if one exists.
   */
  portrait?: (number | null) | Media
  /**
   * The same maker elsewhere: Wikidata, the Getty ULAN.
   */
  sameAs?:
    | {
        url: string
        id?: string | null
      }[]
    | null
  translationStatus: 'entered' | 'machine' | 'reviewed'
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * Images shown on the site. Each is processed from a capture in Masters; the site shows resized copies of it, never this file itself.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  /**
   * What the image shows, for someone who cannot see it. For a map or a print: the region, the cartouche, the colouring, anything notable. For a digital mockup or an AI-generated image, start with what it is.
   */
  alt: string
  /**
   * Baseline: built from the record. AI draft: stays flagged until a person has checked it.
   */
  altSource?: ('baseline' | 'cataloguer' | 'ai-draft') | null
  translationStatus?: ('entered' | 'machine' | 'reviewed') | null
  caption?: string | null
  credit?: string | null
  licence?: string | null
  /**
   * What the image is — set at intake, the same as its master’s.
   */
  role:
    | 'recto'
    | 'verso'
    | 'detail'
    | 'raking'
    | 'transmitted'
    | 'framed'
    | 'in-room'
    | 'scale'
    | 'flat'
    | 'lifestyle'
    | 'packaging'
    | 'showroom'
    | 'room-plate'
    | 'editorial'
  /**
   * How it was made. Anything but a photograph is labelled wherever it is shown. There is no default: choose.
   */
  provenance: 'photograph' | 'composite' | 'rendered' | 'ai-generated'
  /**
   * The capture this image was processed from.
   */
  master?: (number | null) | Master
  /**
   * Derived from the file: the address its derivatives and tiles are stored under.
   */
  assetId?: string | null
  derivatives?: {
    status?: ('pending' | 'ready' | 'failed') | null
    /**
     * The ladder's version once built (now v1).
     */
    version?: string | null
    blurDataUri?: string | null
  }
  iiif?: {
    status?: ('none' | 'pending' | 'ready' | 'failed') | null
  }
  prefix?: string | null
  _objectKey?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * The private files images and print files are made from: every capture as received, and each design’s print file. Never shown on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "masters".
 */
export interface Master {
  id: number
  kind: 'capture' | 'print-file'
  /**
   * Where the file is in the private masters bucket. It has no public URL.
   */
  storageKey: string
  /**
   * The file's SHA-256: checked against what the bucket holds.
   */
  checksum: string
  /**
   * From the bucket.
   */
  byteSize?: number | null
  contentType?: string | null
  widthPx?: number | null
  heightPx?: number | null
  colourProfile?: string | null
  /**
   * The owning brand's slug.
   */
  brand: string
  work?: (number | null) | Work
  design?: (number | null) | Design
  /**
   * What the capture is, as the intake judged it.
   */
  role?:
    | (
        | 'recto'
        | 'verso'
        | 'detail'
        | 'raking'
        | 'transmitted'
        | 'framed'
        | 'in-room'
        | 'scale'
        | 'flat'
        | 'lifestyle'
        | 'packaging'
        | 'showroom'
        | 'room-plate'
        | 'editorial'
        | 'reference'
      )
    | null
  /**
   * How it was made — declared at intake, never inferred. No default.
   */
  provenance?: ('photograph' | 'composite' | 'rendered' | 'ai-generated') | null
  /**
   * The object's bounding box in the frame's pixels — a sheet's outer edge, margins included.
   */
  objectBox?: {
    x?: number | null
    y?: number | null
    width?: number | null
    height?: number | null
  }
  /**
   * The object's pixels over its real size, from the ruler — never the file's DPI tag.
   */
  objectPpi?: number | null
  captureTier?: ('good' | 'better' | 'best') | null
  intake?: {
    batch?: string | null
    /**
     * A stock number, a product, "showroom".
     */
    reference?: string | null
    /**
     * The name it was handed over under.
     */
    receivedAs?: string | null
    verdict?: ('pass' | 'fix-owner' | 'legacy') | null
    retouching?: ('none' | 'unknown' | 'retouched-legacy') | null
    notes?:
      | {
          note: string
          id?: string | null
        }[]
      | null
  }
  updatedAt: string
  createdAt: string
}
/**
 * The objects themselves — each map, print, photograph or book. How one is sold is its product.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number
  /**
   * Made when the work is first saved, and never changed: sister sync and redirects key on it.
   */
  workUid?: string | null
  /**
   * The gallery’s own number: M.1044, P.2098.
   */
  stockNumber?: string | null
  /**
   * The hook title buyers read: "Bali by François Valentijn, 1726 — the first large-scale map of the island". Needed to publish. Required in English, the default language; another language left blank shows the English.
   */
  title?: string | null
  /**
   * As printed, letter for letter: Kaart van het Eyland Bali.
   */
  originalTitle?: string | null
  /**
   * Its language: nl, la, ms.
   */
  originalTitleLanguage?: string | null
  /**
   * What kind of object it is: it decides the HS code and how the page reads.
   */
  objectType?:
    | (
        | 'map'
        | 'sea-chart'
        | 'city-plan'
        | 'view'
        | 'print'
        | 'photograph'
        | 'book'
        | 'atlas'
        | 'poster'
        | 'document'
        | 'ethnographic'
        | 'other'
      )
    | null
  /**
   * Who made it, in what role, and how certain the attribution is.
   */
  makers?:
    | {
        maker: number | Maker
        role:
          | 'cartographer'
          | 'engraver'
          | 'publisher'
          | 'author'
          | 'artist'
          | 'photographer'
          | 'studio'
          | 'printer'
        certainty: 'certain' | 'attributed' | 'after' | 'workshop'
        id?: string | null
      }[]
    | null
  /**
   * When this sheet was printed or issued. Needed to publish.
   */
  date?: {
    precision?: ('exact' | 'circa' | 'before' | 'after' | 'range' | 'unknown') | null
    from?: number | null
    to?: number | null
    /**
     * Your own wording, if the year alone says it wrong: "1724–26".
     */
    display?: string | null
  }
  /**
   * When the work first appeared, if earlier.
   */
  firstEdition?: {
    precision?: ('exact' | 'circa' | 'before' | 'after' | 'range' | 'unknown') | null
    from?: number | null
    to?: number | null
    /**
     * Your own wording, if the year alone says it wrong: "1724–26".
     */
    display?: string | null
  }
  /**
   * The date the plate itself bears, if any.
   */
  dateOnPlate?: {
    precision?: ('exact' | 'circa' | 'before' | 'after' | 'range' | 'unknown') | null
    from?: number | null
    to?: number | null
    /**
     * Your own wording, if the year alone says it wrong: "1724–26".
     */
    display?: string | null
  }
  /**
   * As the imprint and the book it came from say.
   */
  publication?: {
    /**
     * Amsterdam
     */
    place?: string | null
    /**
     * As printed
     */
    publisher?: string | null
    /**
     * From: Oud en Nieuw Oost-Indiën, 1724–26.
     */
    sourceWork?: string | null
    edition?: string | null
    state?: string | null
    /**
     * Of the printed text: nl, la.
     */
    textLanguage?: string | null
    /**
     * "Verso: blank", or the text printed on the back.
     */
    verso?: string | null
  }
  technique?:
    | (
        | 'woodcut'
        | 'wood-engraving'
        | 'copperplate-engraving'
        | 'etching'
        | 'steel-engraving'
        | 'mezzotint'
        | 'aquatint'
        | 'lithograph'
        | 'chromolithograph'
        | 'offset-lithograph'
        | 'screenprint'
        | 'salt-print'
        | 'albumen-print'
        | 'gelatin-silver-print'
        | 'collotype'
        | 'photogravure'
        | 'cyanotype'
        | 'manuscript'
        | 'other'
      )
    | null
  colour?: ('publishers' | 'original-hand' | 'old-hand' | 'later' | 'printed' | 'uncoloured') | null
  /**
   * In millimetres, height before width. Inches are worked out for you.
   */
  dimensions?: {
    /**
     * The printed area: to the plate mark, or the neat line.
     */
    image?: {
      height?: number | null
      width?: number | null
    }
    /**
     * The whole sheet, margins included.
     */
    sheet?: {
      height?: number | null
      width?: number | null
    }
    /**
     * The frame’s outer size, if it is framed.
     */
    framed?: {
      height?: number | null
      width?: number | null
      depth?: number | null
    }
  }
  /**
   * A volume’s collation.
   */
  book?: {
    binding?: string | null
    pagination?: string | null
    plates?: string | null
    completeness?: string | null
    /**
     * Photographs of spreads, in order.
     */
    openings?: (number | Media)[] | null
    spine?: (number | null) | Media
    cover?: (number | null) | Media
  }
  /**
   * One primary place, and up to 5 more as tags.
   */
  places?:
    | {
        place: number | Place
        role: 'depicts' | 'published-at' | 'photographed-at'
        primary?: boolean | null
        id?: string | null
      }[]
    | null
  /**
   * Wayang, Batik, Temples, Spices, VOC, Costume …
   */
  subjects?: (number | Term)[] | null
  /**
   * "Tooley (Australia) 1268", Koeman, Parry numbers.
   */
  references?:
    | {
        source: number | Source
        ref?: string | null
        note?: string | null
        id?: string | null
      }[]
    | null
  /**
   * Who held it before, and when.
   */
  provenance?:
    | {
        holder: string
        period?: string | null
        note?: string | null
        id?: string | null
      }[]
    | null
  /**
   * Other copies of this map: offered when this one has sold.
   */
  sameEdition?: (number | Work)[] | null
  condition?: {
    /**
     * From the brand’s published scale (Terms → Condition grade).
     */
    grade?: (number | null) | Term
    notes?: string | null
    defects?:
      | {
          defect: string
          id?: string | null
        }[]
      | null
    restoration?: string | null
  }
  /**
   * Each image’s role — recto, verso, detail … — is the image’s own. The page leads with the first photographed recto; nothing on a work is AI-generated.
   */
  images?:
    | {
        media: number | Media
        caption?: string | null
        id?: string | null
      }[]
    | null
  /**
   * The recto’s capture its reproductions are made from.
   */
  master?: (number | null) | Master
  /**
   * From the owner’s item register. Left blank, the item publishes as enquiry-only and sells nowhere online.
   */
  physical?: {
    /**
     * Where the object is now.
     */
    location?: (number | null) | Location
    /**
     * Never assumed: set it from the register.
     */
    exportStatus?: ('cleared' | 'domestic-only' | 'permit-pending' | 'not-applicable') | null
    coaIssued?: boolean | null
    acquisition?: {
      source?: string | null
      consignor?: string | null
      date?: string | null
      /**
       * In the currency’s smallest unit: cents, or whole rupiah.
       */
      cost?: {
        amount?: number | null
        currency?: ('IDR' | 'USD' | 'SGD' | 'EUR' | 'AUD' | 'GBP') | null
      }
    }
  }
  /**
   * Whether reproductions may be made and sold from this work.
   */
  rights?: {
    status?: ('public-domain' | 'licensed' | 'rights-pending' | 'restricted' | 'unknown') | null
    holder?: string | null
    licenceRef?: string | null
    /**
     * Two-letter country codes, or WORLD.
     */
    territories?: string[] | null
    expires?: string | null
    /**
     * A reproduction of this work cannot publish while this is off.
     */
    printAllowed?: boolean | null
  }
  /**
   * Set by the sister sync on a copy of a sister’s work: its synced fields are read-only here.
   */
  origin?: {
    brand?: string | null
    workUid?: string | null
    syncedAt?: string | null
  }
  cataloguing?: {
    status?: ('draft' | 'catalogued' | 'verified') | null
    cataloguer?: (number | null) | User
    verifiedAt?: string | null
    /**
     * The work cannot publish while any field is listed here.
     */
    aiDraft?:
      | (
          | 'title'
          | 'originalTitle'
          | 'publication'
          | 'date'
          | 'makers'
          | 'places'
          | 'subjects'
          | 'technique'
          | 'colour'
          | 'condition'
          | 'references'
          | 'seo'
        )[]
      | null
  }
  legacy?: {
    /**
     * The old site’s product id: the public id it keeps.
     */
    productId?: number | null
    sku?: string | null
    url?: string | null
    categories?: string[] | null
  }
  seo?: {
    title?: string | null
    description?: string | null
    image?: (number | null) | Media
  }
  translationStatus: 'entered' | 'machine' | 'reviewed'
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number
  /**
   * The modern name, in each language: Jakarta, Sulawesi, Maluku. Required in English, the default language; another language left blank shows the English.
   */
  name?: string | null
  /**
   * The address of its page. Made once from the name; renaming the record never changes it, so links keep working.
   */
  slug: string
  /**
   * Batavia, Iava, Celebes, Moluccas — every name the place has gone by. Search finds the place under each.
   */
  historicalNames?:
    | {
        name: string
        /**
         * A language code: nl, la, pt, ms, jv.
         */
        language?: string | null
        /**
         * When it was used: "1619–1942", "VOC era".
         */
        period?: string | null
        id?: string | null
      }[]
    | null
  type?:
    | (
        | 'region'
        | 'country'
        | 'island-group'
        | 'island'
        | 'province'
        | 'kingdom'
        | 'city'
        | 'town'
        | 'sea'
        | 'strait'
        | 'ocean'
      )
    | null
  /**
   * The place it lies in: Batavia lies in Java. Leave empty for a top-level place.
   */
  parent?: (number | null) | Place
  /**
   * The places that lie in this one.
   */
  children?: {
    docs?: (number | Place)[]
    hasNextPage?: boolean
    totalDocs?: number
  }
  /**
   * Where it is, in decimal degrees (WGS 84): the point a locator map pins and, if useful, the box a map of it frames.
   */
  geo?: {
    lat?: number | null
    lng?: number | null
    /**
     * West, south, east and north edges. West may be greater than east for a box across the 180° meridian.
     */
    bbox?: {
      west?: number | null
      south?: number | null
      east?: number | null
      north?: number | null
    }
  }
  translationStatus: 'entered' | 'machine' | 'reviewed'
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: number
  /**
   * Fixed once the term is created.
   */
  kind: 'subject' | 'mood' | 'room' | 'occasion' | 'recipient' | 'grade'
  /**
   * As a visitor reads it: "Batik", "VG+". Required in English, the default language; another language left blank shows the English.
   */
  label?: string | null
  /**
   * The address of its page. Made once from the name; renaming the record never changes it, so links keep working.
   */
  slug: string
  /**
   * What the grade means, as the condition legend shows it.
   */
  definition?: string | null
  /**
   * Its A–D equivalent: A, B+, C or B/C.
   */
  equivalent?: string | null
  /**
   * Order within its vocabulary: a grade scale best first.
   */
  position?: number | null
  translationStatus: 'entered' | 'machine' | 'reviewed'
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number
  /**
   * How references cite it: "Tooley", "Koeman", "Tooley (Australia)".
   */
  shortCite: string
  /**
   * The address of its page. Made once from the name; renaming the record never changes it, so links keep working.
   */
  slug: string
  /**
   * The full entry: author, title, place, publisher, year.
   */
  citation?: string | null
  /**
   * The year it was published (the first, for a multi-volume work).
   */
  year?: number | null
  /**
   * Where it can be read or bought online, if anywhere.
   */
  url?: string | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designs".
 */
export interface Design {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curations".
 */
export interface Curation {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types".
 */
export interface ProductType {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-levels".
 */
export interface StockLevel {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions".
 */
export interface Exhibition {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts".
 */
export interface PaymentAttempt {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments".
 */
export interface Shipment {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns".
 */
export interface Return {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consignments".
 */
export interface Consignment {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts".
 */
export interface Discount {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards".
 */
export interface GiftCard {
  id: number
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'customers'
        value: number | Customer
      } | null)
    | ({
        relationTo: 'addresses'
        value: number | Address
      } | null)
    | ({
        relationTo: 'saved-items'
        value: number | SavedItem
      } | null)
    | ({
        relationTo: 'want-lists'
        value: number | WantList
      } | null)
    | ({
        relationTo: 'subscribers'
        value: number | Subscriber
      } | null)
    | ({
        relationTo: 'reviews'
        value: number | Review
      } | null)
    | ({
        relationTo: 'makers'
        value: number | Maker
      } | null)
    | ({
        relationTo: 'places'
        value: number | Place
      } | null)
    | ({
        relationTo: 'terms'
        value: number | Term
      } | null)
    | ({
        relationTo: 'sources'
        value: number | Source
      } | null)
    | ({
        relationTo: 'curations'
        value: number | Curation
      } | null)
    | ({
        relationTo: 'works'
        value: number | Work
      } | null)
    | ({
        relationTo: 'designs'
        value: number | Design
      } | null)
    | ({
        relationTo: 'products'
        value: number | Product
      } | null)
    | ({
        relationTo: 'product-types'
        value: number | ProductType
      } | null)
    | ({
        relationTo: 'variants'
        value: number | Variant
      } | null)
    | ({
        relationTo: 'locations'
        value: number | Location
      } | null)
    | ({
        relationTo: 'stock-levels'
        value: number | StockLevel
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'masters'
        value: number | Master
      } | null)
    | ({
        relationTo: 'stories'
        value: number | Story
      } | null)
    | ({
        relationTo: 'pages'
        value: number | Page
      } | null)
    | ({
        relationTo: 'exhibitions'
        value: number | Exhibition
      } | null)
    | ({
        relationTo: 'redirects'
        value: number | Redirect
      } | null)
    | ({
        relationTo: 'carts'
        value: number | Cart
      } | null)
    | ({
        relationTo: 'reservations'
        value: number | Reservation
      } | null)
    | ({
        relationTo: 'orders'
        value: number | Order
      } | null)
    | ({
        relationTo: 'payment-attempts'
        value: number | PaymentAttempt
      } | null)
    | ({
        relationTo: 'refunds'
        value: number | Refund
      } | null)
    | ({
        relationTo: 'shipments'
        value: number | Shipment
      } | null)
    | ({
        relationTo: 'returns'
        value: number | Return
      } | null)
    | ({
        relationTo: 'offers'
        value: number | Offer
      } | null)
    | ({
        relationTo: 'enquiries'
        value: number | Enquiry
      } | null)
    | ({
        relationTo: 'consignments'
        value: number | Consignment
      } | null)
    | ({
        relationTo: 'appointments'
        value: number | Appointment
      } | null)
    | ({
        relationTo: 'invoices'
        value: number | Invoice
      } | null)
    | ({
        relationTo: 'discounts'
        value: number | Discount
      } | null)
    | ({
        relationTo: 'gift-cards'
        value: number | GiftCard
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  roles?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  resetPasswordRequestedAt?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-items_select".
 */
export interface SavedItemsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "want-lists_select".
 */
export interface WantListsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makers_select".
 */
export interface MakersSelect<T extends boolean = true> {
  name?: T
  sortName?: T
  slug?: T
  aliases?:
    | T
    | {
        name?: T
        id?: T
      }
  roles?: T
  born?:
    | T
    | {
        precision?: T
        from?: T
        to?: T
        display?: T
      }
  died?:
    | T
    | {
        precision?: T
        from?: T
        to?: T
        display?: T
      }
  nationality?: T
  portrait?: T
  sameAs?:
    | T
    | {
        url?: T
        id?: T
      }
  translationStatus?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T
  slug?: T
  historicalNames?:
    | T
    | {
        name?: T
        language?: T
        period?: T
        id?: T
      }
  type?: T
  parent?: T
  children?: T
  geo?:
    | T
    | {
        lat?: T
        lng?: T
        bbox?:
          | T
          | {
              west?: T
              south?: T
              east?: T
              north?: T
            }
      }
  translationStatus?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  kind?: T
  label?: T
  slug?: T
  definition?: T
  equivalent?: T
  position?: T
  translationStatus?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  shortCite?: T
  slug?: T
  citation?: T
  year?: T
  url?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curations_select".
 */
export interface CurationsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  workUid?: T
  stockNumber?: T
  title?: T
  originalTitle?: T
  originalTitleLanguage?: T
  objectType?: T
  makers?:
    | T
    | {
        maker?: T
        role?: T
        certainty?: T
        id?: T
      }
  date?:
    | T
    | {
        precision?: T
        from?: T
        to?: T
        display?: T
      }
  firstEdition?:
    | T
    | {
        precision?: T
        from?: T
        to?: T
        display?: T
      }
  dateOnPlate?:
    | T
    | {
        precision?: T
        from?: T
        to?: T
        display?: T
      }
  publication?:
    | T
    | {
        place?: T
        publisher?: T
        sourceWork?: T
        edition?: T
        state?: T
        textLanguage?: T
        verso?: T
      }
  technique?: T
  colour?: T
  dimensions?:
    | T
    | {
        image?:
          | T
          | {
              height?: T
              width?: T
            }
        sheet?:
          | T
          | {
              height?: T
              width?: T
            }
        framed?:
          | T
          | {
              height?: T
              width?: T
              depth?: T
            }
      }
  book?:
    | T
    | {
        binding?: T
        pagination?: T
        plates?: T
        completeness?: T
        openings?: T
        spine?: T
        cover?: T
      }
  places?:
    | T
    | {
        place?: T
        role?: T
        primary?: T
        id?: T
      }
  subjects?: T
  references?:
    | T
    | {
        source?: T
        ref?: T
        note?: T
        id?: T
      }
  provenance?:
    | T
    | {
        holder?: T
        period?: T
        note?: T
        id?: T
      }
  sameEdition?: T
  condition?:
    | T
    | {
        grade?: T
        notes?: T
        defects?:
          | T
          | {
              defect?: T
              id?: T
            }
        restoration?: T
      }
  images?:
    | T
    | {
        media?: T
        caption?: T
        id?: T
      }
  master?: T
  physical?:
    | T
    | {
        location?: T
        exportStatus?: T
        coaIssued?: T
        acquisition?:
          | T
          | {
              source?: T
              consignor?: T
              date?: T
              cost?:
                | T
                | {
                    amount?: T
                    currency?: T
                  }
            }
      }
  rights?:
    | T
    | {
        status?: T
        holder?: T
        licenceRef?: T
        territories?: T
        expires?: T
        printAllowed?: T
      }
  origin?:
    | T
    | {
        brand?: T
        workUid?: T
        syncedAt?: T
      }
  cataloguing?:
    | T
    | {
        status?: T
        cataloguer?: T
        verifiedAt?: T
        aiDraft?: T
      }
  legacy?:
    | T
    | {
        productId?: T
        sku?: T
        url?: T
        categories?: T
      }
  seo?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  translationStatus?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designs_select".
 */
export interface DesignsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-types_select".
 */
export interface ProductTypesSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-levels_select".
 */
export interface StockLevelsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  altSource?: T
  translationStatus?: T
  caption?: T
  credit?: T
  licence?: T
  role?: T
  provenance?: T
  master?: T
  assetId?: T
  derivatives?:
    | T
    | {
        status?: T
        version?: T
        blurDataUri?: T
      }
  iiif?:
    | T
    | {
        status?: T
      }
  prefix?: T
  _objectKey?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "masters_select".
 */
export interface MastersSelect<T extends boolean = true> {
  kind?: T
  storageKey?: T
  checksum?: T
  byteSize?: T
  contentType?: T
  widthPx?: T
  heightPx?: T
  colourProfile?: T
  brand?: T
  work?: T
  design?: T
  role?: T
  provenance?: T
  objectBox?:
    | T
    | {
        x?: T
        y?: T
        width?: T
        height?: T
      }
  objectPpi?: T
  captureTier?: T
  intake?:
    | T
    | {
        batch?: T
        reference?: T
        receivedAs?: T
        verdict?: T
        retouching?: T
        notes?:
          | T
          | {
              note?: T
              id?: T
            }
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions_select".
 */
export interface ExhibitionsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts_select".
 */
export interface PaymentAttemptsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments_select".
 */
export interface ShipmentsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns_select".
 */
export interface ReturnsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consignments_select".
 */
export interface ConsignmentsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts_select".
 */
export interface DiscountsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards_select".
 */
export interface GiftCardsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-settings".
 */
export interface BrandSetting {
  id: number
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-settings".
 */
export interface CommerceSetting {
  id: number
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent".
 */
export interface Consent {
  id: number
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-settings_select".
 */
export interface BrandSettingsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-settings_select".
 */
export interface CommerceSettingsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent_select".
 */
export interface ConsentSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
