import { sql, type MigrateDownArgs, type MigrateUpArgs } from '@payloadcms/db-postgres'

/**
 * TASKS.md 2.4 — W2's interim migration (2.5 deletes every migration and makes one initial one):
 * the 31 stub collections, the six stub globals and `idempotency_keys` go; `nl` leaves the
 * locales; `users` gets one `role` (`owner` · `editor` · `store`) and a `store`, and a minimal
 * `stores` collection arrives; media and masters lose the room plate, the print file, the brand
 * and the design; works lose the sister copy's `origin` and the `locations` relation.
 *
 * Generated by `migrate:create w2_cms`, then three hand-written steps (marked below):
 * 1. **Refuse what would be lost or fail to cast** — a room-plate image, a print-file master, a
 *    sister copy, `nl` text — so a database holding any stops the deploy with a reason, never
 *    drops it silently. The stubs' tables are dropped as they are: no code ever wrote them.
 * 2. **Carry each user's role across** before `users_roles` goes: `admin` → `owner`, every other
 *    role → `editor` (the owner's team; DR-10). A store user is the owner's to make, with a store.
 * 3. **The last-owner backstop on `users.role`**, replacing `users_roles`' (senior-db review of
 *    3.2, B1, R1, R2): a deferred constraint trigger under `ADMINS_LOCK_KEY` refuses a commit that
 *    leaves users and no owner, and a TRUNCATE of `users` is refused outright.
 *
 * One edit to the generated statements: every `DROP CONSTRAINT` and `DROP INDEX` says
 * `IF EXISTS`. drizzle-kit drops the stubs' tables `CASCADE` first, which already removes the
 * foreign keys that pointed at them, and its later drop of the same key would fail the migration.
 * And `users.role` is added nullable, filled, then made `NOT NULL` (step 2), not added `NOT NULL`.
 */

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`SET LOCAL lock_timeout = '5s'`)

  // Hand-written, step 1: refuse what this migration would otherwise drop or fail to cast.
  await db.execute(sql`
    DO $refuse_loss$
    DECLARE
      found record;
      holds_nl boolean;
    BEGIN
      IF EXISTS (SELECT 1 FROM "media" WHERE "role" = 'room-plate') THEN
        RAISE EXCEPTION 'media still holds room-plate images: delete them before this migration';
      END IF;
      IF EXISTS (SELECT 1 FROM "masters" WHERE "kind" = 'print-file' OR "role" = 'room-plate') THEN
        RAISE EXCEPTION 'masters still holds print files or room plates: delete them first';
      END IF;
      IF EXISTS (SELECT 1 FROM "works" WHERE "origin_work_uid" IS NOT NULL) THEN
        RAISE EXCEPTION 'works still holds sister copies (origin set): delete them first';
      END IF;
      FOR found IN
        SELECT "table_name" FROM information_schema.columns
        WHERE "table_schema" = 'public' AND "column_name" = '_locale' AND "udt_name" = '_locales'
      LOOP
        EXECUTE format(
          'SELECT EXISTS (SELECT 1 FROM %I WHERE "_locale"::text = %L)', found.table_name, 'nl'
        ) INTO holds_nl;
        IF holds_nl THEN
          RAISE EXCEPTION '% still holds Dutch (nl) text: delete it before this migration',
            found.table_name;
        END IF;
      END LOOP;
    END
    $refuse_loss$;
  `)

  // Hand-written, step 2: carry each user's role, and drop the old backstop with its table.
  await db.execute(sql`
    ALTER TABLE "users" ADD COLUMN "role_carried" text;
    UPDATE "users" SET "role_carried" = CASE
      WHEN EXISTS (
        SELECT 1 FROM "users_roles" r WHERE r."parent_id" = "users"."id" AND r."value" = 'admin'
      ) THEN 'owner'
      ELSE 'editor'
    END;
    DROP FUNCTION IF EXISTS "users_keep_an_admin"() CASCADE;
    DROP FUNCTION IF EXISTS "users_roles_refuse_truncate"() CASCADE;
  `)
  await db.execute(sql`
   CREATE TYPE "public"."enum_users_role" AS ENUM('owner', 'editor', 'store');
  CREATE TABLE "stores" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"code" varchar NOT NULL,
  	"name" varchar NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "users_roles" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "customers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "addresses" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "saved_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "want_lists" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "subscribers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "reviews" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "curations" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "designs" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "products" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "product_types" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "variants" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "locations" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "stock_levels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "stories" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "exhibitions" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "redirects" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "carts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "reservations" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orders" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payment_attempts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "refunds" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "shipments" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "returns" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "offers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "enquiries" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "consignments" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "appointments" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "invoices" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "discounts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "gift_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "brand_settings" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "navigation" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "homepage" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "commerce_settings" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "consent" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "seo_defaults" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "idempotency_keys" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "users_roles" CASCADE;
  DROP TABLE "customers" CASCADE;
  DROP TABLE "addresses" CASCADE;
  DROP TABLE "saved_items" CASCADE;
  DROP TABLE "want_lists" CASCADE;
  DROP TABLE "subscribers" CASCADE;
  DROP TABLE "reviews" CASCADE;
  DROP TABLE "curations" CASCADE;
  DROP TABLE "designs" CASCADE;
  DROP TABLE "products" CASCADE;
  DROP TABLE "product_types" CASCADE;
  DROP TABLE "variants" CASCADE;
  DROP TABLE "locations" CASCADE;
  DROP TABLE "stock_levels" CASCADE;
  DROP TABLE "stories" CASCADE;
  DROP TABLE "pages" CASCADE;
  DROP TABLE "exhibitions" CASCADE;
  DROP TABLE "redirects" CASCADE;
  DROP TABLE "carts" CASCADE;
  DROP TABLE "reservations" CASCADE;
  DROP TABLE "orders" CASCADE;
  DROP TABLE "payment_attempts" CASCADE;
  DROP TABLE "refunds" CASCADE;
  DROP TABLE "shipments" CASCADE;
  DROP TABLE "returns" CASCADE;
  DROP TABLE "offers" CASCADE;
  DROP TABLE "enquiries" CASCADE;
  DROP TABLE "consignments" CASCADE;
  DROP TABLE "appointments" CASCADE;
  DROP TABLE "invoices" CASCADE;
  DROP TABLE "discounts" CASCADE;
  DROP TABLE "gift_cards" CASCADE;
  DROP TABLE "brand_settings" CASCADE;
  DROP TABLE "navigation" CASCADE;
  DROP TABLE "homepage" CASCADE;
  DROP TABLE "commerce_settings" CASCADE;
  DROP TABLE "consent" CASCADE;
  DROP TABLE "seo_defaults" CASCADE;
  DROP TABLE "idempotency_keys" CASCADE;
  ALTER TABLE "works" DROP CONSTRAINT IF EXISTS "works_physical_location_id_locations_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT IF EXISTS "_works_v_version_physical_location_id_locations_id_fk";
  
  ALTER TABLE "masters" DROP CONSTRAINT IF EXISTS "masters_design_id_designs_id_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_customers_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_addresses_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_saved_items_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_want_lists_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_subscribers_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_reviews_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_curations_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_designs_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_products_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_product_types_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_variants_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_locations_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_stock_levels_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_stories_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_pages_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_exhibitions_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_redirects_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_carts_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_reservations_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_orders_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_payment_attempts_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_refunds_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_shipments_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_returns_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_offers_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_enquiries_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_consignments_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_appointments_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_invoices_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_discounts_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_gift_cards_fk";
  
  ALTER TABLE "works_references_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "works_provenance_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "works_condition_defects_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "works_images_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "works_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_works_v_version_references_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_works_v_version_provenance_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_works_v_version_condition_defects_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_works_v_version_images_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_works_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "makers_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_makers_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "places_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_places_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "terms_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "_terms_v_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  ALTER TABLE "media_locales" ALTER COLUMN "_locale" SET DATA TYPE text;
  DROP TYPE "public"."_locales";
  CREATE TYPE "public"."_locales" AS ENUM('en', 'id');
  ALTER TABLE "works_references_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "works_provenance_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "works_condition_defects_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "works_images_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "works_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_works_v_version_references_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_works_v_version_provenance_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_works_v_version_condition_defects_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_works_v_version_images_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_works_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "makers_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_makers_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "places_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_places_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "terms_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_terms_v_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "media_locales" ALTER COLUMN "_locale" SET DATA TYPE "public"."_locales" USING "_locale"::"public"."_locales";
  ALTER TABLE "_makers_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__makers_v_published_locale";
  CREATE TYPE "public"."enum__makers_v_published_locale" AS ENUM('en', 'id');
  ALTER TABLE "_makers_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__makers_v_published_locale" USING "published_locale"::"public"."enum__makers_v_published_locale";
  ALTER TABLE "_places_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__places_v_published_locale";
  CREATE TYPE "public"."enum__places_v_published_locale" AS ENUM('en', 'id');
  ALTER TABLE "_places_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__places_v_published_locale" USING "published_locale"::"public"."enum__places_v_published_locale";
  ALTER TABLE "_terms_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__terms_v_published_locale";
  CREATE TYPE "public"."enum__terms_v_published_locale" AS ENUM('en', 'id');
  ALTER TABLE "_terms_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__terms_v_published_locale" USING "published_locale"::"public"."enum__terms_v_published_locale";
  ALTER TABLE "_sources_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__sources_v_published_locale";
  CREATE TYPE "public"."enum__sources_v_published_locale" AS ENUM('en', 'id');
  ALTER TABLE "_sources_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__sources_v_published_locale" USING "published_locale"::"public"."enum__sources_v_published_locale";
  ALTER TABLE "_works_v" ALTER COLUMN "published_locale" SET DATA TYPE text;
  DROP TYPE "public"."enum__works_v_published_locale";
  CREATE TYPE "public"."enum__works_v_published_locale" AS ENUM('en', 'id');
  ALTER TABLE "_works_v" ALTER COLUMN "published_locale" SET DATA TYPE "public"."enum__works_v_published_locale" USING "published_locale"::"public"."enum__works_v_published_locale";
  ALTER TABLE "media" ALTER COLUMN "role" SET DATA TYPE text;
  DROP TYPE "public"."enum_media_role";
  CREATE TYPE "public"."enum_media_role" AS ENUM('recto', 'verso', 'detail', 'raking', 'transmitted', 'framed', 'in-room', 'scale', 'flat', 'lifestyle', 'packaging', 'showroom', 'editorial');
  ALTER TABLE "media" ALTER COLUMN "role" SET DATA TYPE "public"."enum_media_role" USING "role"::"public"."enum_media_role";
  ALTER TABLE "masters" ALTER COLUMN "kind" SET DATA TYPE text;
  DROP TYPE "public"."enum_masters_kind";
  CREATE TYPE "public"."enum_masters_kind" AS ENUM('capture');
  ALTER TABLE "masters" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_masters_kind" USING "kind"::"public"."enum_masters_kind";
  ALTER TABLE "masters" ALTER COLUMN "role" SET DATA TYPE text;
  DROP TYPE "public"."enum_masters_role";
  CREATE TYPE "public"."enum_masters_role" AS ENUM('recto', 'verso', 'detail', 'raking', 'transmitted', 'framed', 'in-room', 'scale', 'flat', 'lifestyle', 'packaging', 'showroom', 'editorial', 'reference');
  ALTER TABLE "masters" ALTER COLUMN "role" SET DATA TYPE "public"."enum_masters_role" USING "role"::"public"."enum_masters_role";
  DROP INDEX IF EXISTS "works_physical_physical_location_idx";
  DROP INDEX IF EXISTS "works_origin_origin_work_uid_idx";
  DROP INDEX IF EXISTS "_works_v_version_physical_version_physical_location_idx";
  DROP INDEX IF EXISTS "_works_v_version_origin_version_origin_work_uid_idx";
  DROP INDEX IF EXISTS "masters_design_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_customers_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_addresses_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_saved_items_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_want_lists_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_subscribers_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_reviews_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_curations_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_designs_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_products_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_product_types_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_variants_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_locations_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_stock_levels_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_stories_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_pages_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_exhibitions_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_redirects_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_carts_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_reservations_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_orders_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_payment_attempts_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_refunds_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_shipments_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_returns_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_offers_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_enquiries_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_consignments_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_appointments_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_invoices_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_discounts_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_gift_cards_id_idx";
  ALTER TABLE "users" ADD COLUMN "role" "enum_users_role";
  ALTER TABLE "users" ADD COLUMN "store_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "stores_id" integer;
  CREATE UNIQUE INDEX "stores_code_idx" ON "stores" USING btree ("code");
  CREATE INDEX "stores_updated_at_idx" ON "stores" USING btree ("updated_at");
  CREATE INDEX "stores_created_at_idx" ON "stores" USING btree ("created_at");
  ALTER TABLE "users" ADD CONSTRAINT "users_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_stores_fk" FOREIGN KEY ("stores_id") REFERENCES "public"."stores"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "users_role_idx" ON "users" USING btree ("role");
  CREATE INDEX "users_store_idx" ON "users" USING btree ("store_id");
  CREATE INDEX "payload_locked_documents_rels_stores_id_idx" ON "payload_locked_documents_rels" USING btree ("stores_id");
  ALTER TABLE "works" DROP COLUMN "physical_location_id";
  ALTER TABLE "works" DROP COLUMN "origin_brand";
  ALTER TABLE "works" DROP COLUMN "origin_work_uid";
  ALTER TABLE "works" DROP COLUMN "origin_synced_at";
  ALTER TABLE "_works_v" DROP COLUMN "version_physical_location_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_origin_brand";
  ALTER TABLE "_works_v" DROP COLUMN "version_origin_work_uid";
  ALTER TABLE "_works_v" DROP COLUMN "version_origin_synced_at";
  ALTER TABLE "masters" DROP COLUMN "brand";
  ALTER TABLE "masters" DROP COLUMN "design_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "customers_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "addresses_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "saved_items_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "want_lists_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "subscribers_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "reviews_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "curations_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "designs_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "products_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "product_types_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "variants_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "locations_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "stock_levels_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "stories_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "pages_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "exhibitions_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "redirects_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "carts_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "reservations_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "orders_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "payment_attempts_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "refunds_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "shipments_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "returns_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "offers_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "enquiries_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "consignments_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "appointments_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "invoices_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "discounts_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "gift_cards_id";
  DROP TYPE "public"."enum_users_roles";`)

  // Hand-written, step 2 (end): the carried roles land, and the column becomes required.
  await db.execute(sql`
    UPDATE "users" SET "role" = "role_carried"::"enum_users_role";
    ALTER TABLE "users" DROP COLUMN "role_carried";
    ALTER TABLE "users" ALTER COLUMN "role" SET NOT NULL;
  `)

  // Hand-written, step 3: the database refuses any transaction that leaves users and no owner —
  // the backstop for a path the users hooks never see (raw SQL, a bulk write, two demotions
  // racing). Deferred to COMMIT, and it takes the hooks' own advisory lock first
  // (ADMINS_LOCK_KEY, collections/users/guards.ts), so two committing transactions are checked
  // one after the other and the second sees the first's demotion. With one `role` column it fires
  // only when an owner's role really changes or an owner row is deleted — never on a sign-in that
  // updates the row's lockout counters — and the hooks take the lock before the row lock on every
  // save of an owner's role, so two writers never wait on each other in opposite orders (R1).
  // A dev-pushed database lacks it: triggers are not drizzle schema, so its test runs migrated.
  await db.execute(sql`
    CREATE FUNCTION "users_keep_an_owner"() RETURNS trigger LANGUAGE plpgsql AS $keep_an_owner$
    BEGIN
      PERFORM pg_advisory_xact_lock(-9011197146015594413);
      IF EXISTS (SELECT 1 FROM "users")
        AND NOT EXISTS (SELECT 1 FROM "users" WHERE "role" = 'owner') THEN
        RAISE EXCEPTION 'the last owner cannot lose the owner role or be deleted'
          USING ERRCODE = 'check_violation';
      END IF;
      RETURN NULL;
    END
    $keep_an_owner$;
    CREATE CONSTRAINT TRIGGER "users_keep_an_owner_on_update"
      AFTER UPDATE OF "role" ON "users"
      DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW
      WHEN (OLD."role" = 'owner' AND NEW."role" IS DISTINCT FROM 'owner')
      EXECUTE FUNCTION "users_keep_an_owner"();
    CREATE CONSTRAINT TRIGGER "users_keep_an_owner_on_delete"
      AFTER DELETE ON "users"
      DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW
      WHEN (OLD."role" = 'owner')
      EXECUTE FUNCTION "users_keep_an_owner"();
  `)

  // Hand-written, step 3 (R2): TRUNCATE fires no row trigger, so it would empty users past the
  // one above. A statement-level trigger refuses it outright (also when a TRUNCATE of stores
  // cascades here); staff are removed with DELETE, which the hooks and the trigger judge.
  await db.execute(sql`
    CREATE FUNCTION "users_refuse_truncate"() RETURNS trigger LANGUAGE plpgsql AS $refuse$
    BEGIN
      RAISE EXCEPTION 'users is never truncated: delete staff so the last owner stays one'
        USING ERRCODE = 'check_violation';
    END
    $refuse$;
    CREATE TRIGGER "users_no_truncate"
      BEFORE TRUNCATE ON "users"
      FOR EACH STATEMENT
      EXECUTE FUNCTION "users_refuse_truncate"();
  `)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  // Hand-written: the new backstop goes first, and each role is carried back (owner → admin,
  // anyone else → editor) once the generated statements have rebuilt users_roles.
  await db.execute(sql`
    DROP FUNCTION IF EXISTS "users_keep_an_owner"() CASCADE;
    DROP FUNCTION IF EXISTS "users_refuse_truncate"() CASCADE;
    ALTER TABLE "users" ADD COLUMN "roles_carried" text;
    UPDATE "users" SET "roles_carried" = CASE WHEN "role" = 'owner' THEN 'admin' ELSE 'editor' END;
  `)
  await db.execute(sql`
   CREATE TYPE "public"."enum_users_roles" AS ENUM('admin', 'manager', 'cataloguer', 'editor', 'fulfilment', 'analyst', 'contributor');
  ALTER TYPE "public"."_locales" ADD VALUE 'nl';
  ALTER TYPE "public"."enum__works_v_published_locale" ADD VALUE 'nl';
  ALTER TYPE "public"."enum__makers_v_published_locale" ADD VALUE 'nl';
  ALTER TYPE "public"."enum__places_v_published_locale" ADD VALUE 'nl';
  ALTER TYPE "public"."enum__terms_v_published_locale" ADD VALUE 'nl';
  ALTER TYPE "public"."enum__sources_v_published_locale" ADD VALUE 'nl';
  ALTER TYPE "public"."enum_media_role" ADD VALUE 'room-plate' BEFORE 'editorial';
  ALTER TYPE "public"."enum_masters_kind" ADD VALUE 'print-file';
  ALTER TYPE "public"."enum_masters_role" ADD VALUE 'room-plate' BEFORE 'editorial';
  CREATE TABLE "users_roles" (
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"value" "enum_users_roles",
  	"id" serial PRIMARY KEY NOT NULL
  );
  
  CREATE TABLE "customers" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "addresses" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "saved_items" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "want_lists" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "subscribers" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "reviews" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "curations" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "designs" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "products" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "product_types" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "variants" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "locations" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "stock_levels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "stories" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "pages" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "exhibitions" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "redirects" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "carts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "reservations" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "orders" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "payment_attempts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "refunds" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "shipments" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "returns" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "offers" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "enquiries" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "consignments" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "appointments" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "invoices" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "discounts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "gift_cards" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "brand_settings" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "navigation" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "homepage" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "commerce_settings" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "consent" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "seo_defaults" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "idempotency_keys" (
  	"operation" text COLLATE "C" NOT NULL,
  	"key" text COLLATE "C" NOT NULL,
  	"caller_ref" text COLLATE "C",
  	"request_sha256" text NOT NULL,
  	"response" jsonb,
  	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
  	CONSTRAINT "idempotency_keys_operation_key_unique" UNIQUE("operation","key"),
  	CONSTRAINT "idempotency_keys_request_sha256_hex" CHECK ("request_sha256" ~ '^[0-9a-f]{64}$'),
  	CONSTRAINT "idempotency_keys_key_length" CHECK (length("key") BETWEEN 1 AND 128),
  	CONSTRAINT "idempotency_keys_operation_length" CHECK (length("operation") BETWEEN 1 AND 64)
  );
  
  ALTER TABLE "stores" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "stores" CASCADE;
  ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_store_id_stores_id_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_stores_fk";
  
  DROP INDEX IF EXISTS "users_role_idx";
  DROP INDEX IF EXISTS "users_store_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_stores_id_idx";
  ALTER TABLE "works" ADD COLUMN "physical_location_id" integer;
  ALTER TABLE "works" ADD COLUMN "origin_brand" varchar;
  ALTER TABLE "works" ADD COLUMN "origin_work_uid" varchar;
  ALTER TABLE "works" ADD COLUMN "origin_synced_at" timestamp(3) with time zone;
  ALTER TABLE "_works_v" ADD COLUMN "version_physical_location_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_origin_brand" varchar;
  ALTER TABLE "_works_v" ADD COLUMN "version_origin_work_uid" varchar;
  ALTER TABLE "_works_v" ADD COLUMN "version_origin_synced_at" timestamp(3) with time zone;
  ALTER TABLE "masters" ADD COLUMN "brand" varchar NOT NULL;
  ALTER TABLE "masters" ADD COLUMN "design_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "customers_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "addresses_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "saved_items_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "want_lists_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "subscribers_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "reviews_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "curations_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "designs_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "products_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "product_types_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "variants_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "locations_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "stock_levels_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "stories_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "pages_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "exhibitions_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "redirects_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "carts_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "reservations_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "orders_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "payment_attempts_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "refunds_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "shipments_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "returns_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "offers_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "enquiries_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "consignments_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "appointments_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "invoices_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "discounts_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "gift_cards_id" integer;
  ALTER TABLE "users_roles" ADD CONSTRAINT "users_roles_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "users_roles_order_idx" ON "users_roles" USING btree ("order");
  CREATE INDEX "users_roles_parent_idx" ON "users_roles" USING btree ("parent_id");
  CREATE INDEX "customers_updated_at_idx" ON "customers" USING btree ("updated_at");
  CREATE INDEX "customers_created_at_idx" ON "customers" USING btree ("created_at");
  CREATE INDEX "addresses_updated_at_idx" ON "addresses" USING btree ("updated_at");
  CREATE INDEX "addresses_created_at_idx" ON "addresses" USING btree ("created_at");
  CREATE INDEX "saved_items_updated_at_idx" ON "saved_items" USING btree ("updated_at");
  CREATE INDEX "saved_items_created_at_idx" ON "saved_items" USING btree ("created_at");
  CREATE INDEX "want_lists_updated_at_idx" ON "want_lists" USING btree ("updated_at");
  CREATE INDEX "want_lists_created_at_idx" ON "want_lists" USING btree ("created_at");
  CREATE INDEX "subscribers_updated_at_idx" ON "subscribers" USING btree ("updated_at");
  CREATE INDEX "subscribers_created_at_idx" ON "subscribers" USING btree ("created_at");
  CREATE INDEX "reviews_updated_at_idx" ON "reviews" USING btree ("updated_at");
  CREATE INDEX "reviews_created_at_idx" ON "reviews" USING btree ("created_at");
  CREATE INDEX "curations_updated_at_idx" ON "curations" USING btree ("updated_at");
  CREATE INDEX "curations_created_at_idx" ON "curations" USING btree ("created_at");
  CREATE INDEX "designs_updated_at_idx" ON "designs" USING btree ("updated_at");
  CREATE INDEX "designs_created_at_idx" ON "designs" USING btree ("created_at");
  CREATE INDEX "products_updated_at_idx" ON "products" USING btree ("updated_at");
  CREATE INDEX "products_created_at_idx" ON "products" USING btree ("created_at");
  CREATE INDEX "product_types_updated_at_idx" ON "product_types" USING btree ("updated_at");
  CREATE INDEX "product_types_created_at_idx" ON "product_types" USING btree ("created_at");
  CREATE INDEX "variants_updated_at_idx" ON "variants" USING btree ("updated_at");
  CREATE INDEX "variants_created_at_idx" ON "variants" USING btree ("created_at");
  CREATE INDEX "locations_updated_at_idx" ON "locations" USING btree ("updated_at");
  CREATE INDEX "locations_created_at_idx" ON "locations" USING btree ("created_at");
  CREATE INDEX "stock_levels_updated_at_idx" ON "stock_levels" USING btree ("updated_at");
  CREATE INDEX "stock_levels_created_at_idx" ON "stock_levels" USING btree ("created_at");
  CREATE INDEX "stories_updated_at_idx" ON "stories" USING btree ("updated_at");
  CREATE INDEX "stories_created_at_idx" ON "stories" USING btree ("created_at");
  CREATE INDEX "pages_updated_at_idx" ON "pages" USING btree ("updated_at");
  CREATE INDEX "pages_created_at_idx" ON "pages" USING btree ("created_at");
  CREATE INDEX "exhibitions_updated_at_idx" ON "exhibitions" USING btree ("updated_at");
  CREATE INDEX "exhibitions_created_at_idx" ON "exhibitions" USING btree ("created_at");
  CREATE INDEX "redirects_updated_at_idx" ON "redirects" USING btree ("updated_at");
  CREATE INDEX "redirects_created_at_idx" ON "redirects" USING btree ("created_at");
  CREATE INDEX "carts_updated_at_idx" ON "carts" USING btree ("updated_at");
  CREATE INDEX "carts_created_at_idx" ON "carts" USING btree ("created_at");
  CREATE INDEX "reservations_updated_at_idx" ON "reservations" USING btree ("updated_at");
  CREATE INDEX "reservations_created_at_idx" ON "reservations" USING btree ("created_at");
  CREATE INDEX "orders_updated_at_idx" ON "orders" USING btree ("updated_at");
  CREATE INDEX "orders_created_at_idx" ON "orders" USING btree ("created_at");
  CREATE INDEX "payment_attempts_updated_at_idx" ON "payment_attempts" USING btree ("updated_at");
  CREATE INDEX "payment_attempts_created_at_idx" ON "payment_attempts" USING btree ("created_at");
  CREATE INDEX "refunds_updated_at_idx" ON "refunds" USING btree ("updated_at");
  CREATE INDEX "refunds_created_at_idx" ON "refunds" USING btree ("created_at");
  CREATE INDEX "shipments_updated_at_idx" ON "shipments" USING btree ("updated_at");
  CREATE INDEX "shipments_created_at_idx" ON "shipments" USING btree ("created_at");
  CREATE INDEX "returns_updated_at_idx" ON "returns" USING btree ("updated_at");
  CREATE INDEX "returns_created_at_idx" ON "returns" USING btree ("created_at");
  CREATE INDEX "offers_updated_at_idx" ON "offers" USING btree ("updated_at");
  CREATE INDEX "offers_created_at_idx" ON "offers" USING btree ("created_at");
  CREATE INDEX "enquiries_updated_at_idx" ON "enquiries" USING btree ("updated_at");
  CREATE INDEX "enquiries_created_at_idx" ON "enquiries" USING btree ("created_at");
  CREATE INDEX "consignments_updated_at_idx" ON "consignments" USING btree ("updated_at");
  CREATE INDEX "consignments_created_at_idx" ON "consignments" USING btree ("created_at");
  CREATE INDEX "appointments_updated_at_idx" ON "appointments" USING btree ("updated_at");
  CREATE INDEX "appointments_created_at_idx" ON "appointments" USING btree ("created_at");
  CREATE INDEX "invoices_updated_at_idx" ON "invoices" USING btree ("updated_at");
  CREATE INDEX "invoices_created_at_idx" ON "invoices" USING btree ("created_at");
  CREATE INDEX "discounts_updated_at_idx" ON "discounts" USING btree ("updated_at");
  CREATE INDEX "discounts_created_at_idx" ON "discounts" USING btree ("created_at");
  CREATE INDEX "gift_cards_updated_at_idx" ON "gift_cards" USING btree ("updated_at");
  CREATE INDEX "gift_cards_created_at_idx" ON "gift_cards" USING btree ("created_at");
  CREATE INDEX "idempotency_keys_created_at_idx" ON "idempotency_keys" USING btree ("created_at");
  CREATE INDEX "idempotency_keys_caller_ref_idx" ON "idempotency_keys" USING btree ("caller_ref") WHERE "caller_ref" IS NOT NULL;
  ALTER TABLE "works" ADD CONSTRAINT "works_physical_location_id_locations_id_fk" FOREIGN KEY ("physical_location_id") REFERENCES "public"."locations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_physical_location_id_locations_id_fk" FOREIGN KEY ("version_physical_location_id") REFERENCES "public"."locations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "masters" ADD CONSTRAINT "masters_design_id_designs_id_fk" FOREIGN KEY ("design_id") REFERENCES "public"."designs"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_customers_fk" FOREIGN KEY ("customers_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_addresses_fk" FOREIGN KEY ("addresses_id") REFERENCES "public"."addresses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_saved_items_fk" FOREIGN KEY ("saved_items_id") REFERENCES "public"."saved_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_want_lists_fk" FOREIGN KEY ("want_lists_id") REFERENCES "public"."want_lists"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_subscribers_fk" FOREIGN KEY ("subscribers_id") REFERENCES "public"."subscribers"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_reviews_fk" FOREIGN KEY ("reviews_id") REFERENCES "public"."reviews"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_curations_fk" FOREIGN KEY ("curations_id") REFERENCES "public"."curations"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_designs_fk" FOREIGN KEY ("designs_id") REFERENCES "public"."designs"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_products_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_product_types_fk" FOREIGN KEY ("product_types_id") REFERENCES "public"."product_types"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_variants_fk" FOREIGN KEY ("variants_id") REFERENCES "public"."variants"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_locations_fk" FOREIGN KEY ("locations_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_stock_levels_fk" FOREIGN KEY ("stock_levels_id") REFERENCES "public"."stock_levels"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_stories_fk" FOREIGN KEY ("stories_id") REFERENCES "public"."stories"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_exhibitions_fk" FOREIGN KEY ("exhibitions_id") REFERENCES "public"."exhibitions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_redirects_fk" FOREIGN KEY ("redirects_id") REFERENCES "public"."redirects"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_carts_fk" FOREIGN KEY ("carts_id") REFERENCES "public"."carts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_reservations_fk" FOREIGN KEY ("reservations_id") REFERENCES "public"."reservations"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_orders_fk" FOREIGN KEY ("orders_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_payment_attempts_fk" FOREIGN KEY ("payment_attempts_id") REFERENCES "public"."payment_attempts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_refunds_fk" FOREIGN KEY ("refunds_id") REFERENCES "public"."refunds"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_shipments_fk" FOREIGN KEY ("shipments_id") REFERENCES "public"."shipments"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_returns_fk" FOREIGN KEY ("returns_id") REFERENCES "public"."returns"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_offers_fk" FOREIGN KEY ("offers_id") REFERENCES "public"."offers"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_enquiries_fk" FOREIGN KEY ("enquiries_id") REFERENCES "public"."enquiries"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_consignments_fk" FOREIGN KEY ("consignments_id") REFERENCES "public"."consignments"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_appointments_fk" FOREIGN KEY ("appointments_id") REFERENCES "public"."appointments"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_invoices_fk" FOREIGN KEY ("invoices_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_discounts_fk" FOREIGN KEY ("discounts_id") REFERENCES "public"."discounts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_gift_cards_fk" FOREIGN KEY ("gift_cards_id") REFERENCES "public"."gift_cards"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "works_physical_physical_location_idx" ON "works" USING btree ("physical_location_id");
  CREATE INDEX "works_origin_origin_work_uid_idx" ON "works" USING btree ("origin_work_uid");
  CREATE INDEX "_works_v_version_physical_version_physical_location_idx" ON "_works_v" USING btree ("version_physical_location_id");
  CREATE INDEX "_works_v_version_origin_version_origin_work_uid_idx" ON "_works_v" USING btree ("version_origin_work_uid");
  CREATE INDEX "masters_design_idx" ON "masters" USING btree ("design_id");
  CREATE INDEX "payload_locked_documents_rels_customers_id_idx" ON "payload_locked_documents_rels" USING btree ("customers_id");
  CREATE INDEX "payload_locked_documents_rels_addresses_id_idx" ON "payload_locked_documents_rels" USING btree ("addresses_id");
  CREATE INDEX "payload_locked_documents_rels_saved_items_id_idx" ON "payload_locked_documents_rels" USING btree ("saved_items_id");
  CREATE INDEX "payload_locked_documents_rels_want_lists_id_idx" ON "payload_locked_documents_rels" USING btree ("want_lists_id");
  CREATE INDEX "payload_locked_documents_rels_subscribers_id_idx" ON "payload_locked_documents_rels" USING btree ("subscribers_id");
  CREATE INDEX "payload_locked_documents_rels_reviews_id_idx" ON "payload_locked_documents_rels" USING btree ("reviews_id");
  CREATE INDEX "payload_locked_documents_rels_curations_id_idx" ON "payload_locked_documents_rels" USING btree ("curations_id");
  CREATE INDEX "payload_locked_documents_rels_designs_id_idx" ON "payload_locked_documents_rels" USING btree ("designs_id");
  CREATE INDEX "payload_locked_documents_rels_products_id_idx" ON "payload_locked_documents_rels" USING btree ("products_id");
  CREATE INDEX "payload_locked_documents_rels_product_types_id_idx" ON "payload_locked_documents_rels" USING btree ("product_types_id");
  CREATE INDEX "payload_locked_documents_rels_variants_id_idx" ON "payload_locked_documents_rels" USING btree ("variants_id");
  CREATE INDEX "payload_locked_documents_rels_locations_id_idx" ON "payload_locked_documents_rels" USING btree ("locations_id");
  CREATE INDEX "payload_locked_documents_rels_stock_levels_id_idx" ON "payload_locked_documents_rels" USING btree ("stock_levels_id");
  CREATE INDEX "payload_locked_documents_rels_stories_id_idx" ON "payload_locked_documents_rels" USING btree ("stories_id");
  CREATE INDEX "payload_locked_documents_rels_pages_id_idx" ON "payload_locked_documents_rels" USING btree ("pages_id");
  CREATE INDEX "payload_locked_documents_rels_exhibitions_id_idx" ON "payload_locked_documents_rels" USING btree ("exhibitions_id");
  CREATE INDEX "payload_locked_documents_rels_redirects_id_idx" ON "payload_locked_documents_rels" USING btree ("redirects_id");
  CREATE INDEX "payload_locked_documents_rels_carts_id_idx" ON "payload_locked_documents_rels" USING btree ("carts_id");
  CREATE INDEX "payload_locked_documents_rels_reservations_id_idx" ON "payload_locked_documents_rels" USING btree ("reservations_id");
  CREATE INDEX "payload_locked_documents_rels_orders_id_idx" ON "payload_locked_documents_rels" USING btree ("orders_id");
  CREATE INDEX "payload_locked_documents_rels_payment_attempts_id_idx" ON "payload_locked_documents_rels" USING btree ("payment_attempts_id");
  CREATE INDEX "payload_locked_documents_rels_refunds_id_idx" ON "payload_locked_documents_rels" USING btree ("refunds_id");
  CREATE INDEX "payload_locked_documents_rels_shipments_id_idx" ON "payload_locked_documents_rels" USING btree ("shipments_id");
  CREATE INDEX "payload_locked_documents_rels_returns_id_idx" ON "payload_locked_documents_rels" USING btree ("returns_id");
  CREATE INDEX "payload_locked_documents_rels_offers_id_idx" ON "payload_locked_documents_rels" USING btree ("offers_id");
  CREATE INDEX "payload_locked_documents_rels_enquiries_id_idx" ON "payload_locked_documents_rels" USING btree ("enquiries_id");
  CREATE INDEX "payload_locked_documents_rels_consignments_id_idx" ON "payload_locked_documents_rels" USING btree ("consignments_id");
  CREATE INDEX "payload_locked_documents_rels_appointments_id_idx" ON "payload_locked_documents_rels" USING btree ("appointments_id");
  CREATE INDEX "payload_locked_documents_rels_invoices_id_idx" ON "payload_locked_documents_rels" USING btree ("invoices_id");
  CREATE INDEX "payload_locked_documents_rels_discounts_id_idx" ON "payload_locked_documents_rels" USING btree ("discounts_id");
  CREATE INDEX "payload_locked_documents_rels_gift_cards_id_idx" ON "payload_locked_documents_rels" USING btree ("gift_cards_id");
  ALTER TABLE "users" DROP COLUMN "role";
  ALTER TABLE "users" DROP COLUMN "store_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "stores_id";
  DROP TYPE "public"."enum_users_role";`)

  // Hand-written: the roles back into users_roles, and the old backstop on it (initial migration).
  await db.execute(sql`
    INSERT INTO "users_roles" ("order", "parent_id", "value")
      SELECT 1, "id", "roles_carried"::"enum_users_roles" FROM "users";
    ALTER TABLE "users" DROP COLUMN "roles_carried";
    CREATE FUNCTION "users_keep_an_admin"() RETURNS trigger LANGUAGE plpgsql AS $keep_an_admin$
    BEGIN
      PERFORM pg_advisory_xact_lock(-9011197146015594413);
      IF EXISTS (SELECT 1 FROM "users")
        AND NOT EXISTS (SELECT 1 FROM "users_roles" WHERE "value" = 'admin') THEN
        RAISE EXCEPTION 'the last admin cannot lose the admin role or be deleted'
          USING ERRCODE = 'check_violation';
      END IF;
      RETURN NULL;
    END
    $keep_an_admin$;
    CREATE CONSTRAINT TRIGGER "users_roles_keep_an_admin"
      AFTER UPDATE OR DELETE ON "users_roles"
      DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW
      WHEN (OLD."value" = 'admin')
      EXECUTE FUNCTION "users_keep_an_admin"();
    CREATE FUNCTION "users_roles_refuse_truncate"() RETURNS trigger LANGUAGE plpgsql AS $refuse$
    BEGIN
      RAISE EXCEPTION 'users_roles is never truncated: delete staff so the last admin stays one'
        USING ERRCODE = 'check_violation';
    END
    $refuse$;
    CREATE TRIGGER "users_roles_no_truncate"
      BEFORE TRUNCATE ON "users_roles"
      FOR EACH STATEMENT
      EXECUTE FUNCTION "users_roles_refuse_truncate"();
  `)
}
