import { sql, type MigrateDownArgs, type MigrateUpArgs } from '@payloadcms/db-postgres'

/**
 * TASKS.md 3.5.a — phase 3 wave 1's one migration, after `20261002_073156_initial`: 3.2's
 * catalogue changes (works' public id, status, location, asking price and per-field AI drafts;
 * `sources` folded into plain-text `references`; media's subject), 3.3's shop (products, stores'
 * address and pin, stock levels, orders, payment events, discounts), 3.4's leads, partners, chat
 * sessions, events, pages, redirects and the `site-settings` global, and 3.5's record of role
 * and store changes on `users` (`accessChanges`, SECURITY.md R7).
 *
 * A new migration rather than a fold into the initial: the initial carries hand-written DDL
 * (extensions, the last-owner backstop, the truncate refusals) that 2.5 proved on its own, and
 * 3.1.d deploys it to Helios as is; a second file leaves both reviewable apart.
 *
 * Generated by `migrate:create indies_wave_3_1` against the initial's snapshot, every
 * drizzle-kit "created or renamed?" answered "create" (nothing here is a rename: `sources` and
 * the old `aiDraft` list are gone, not moved). The 20 constraints of the constraint seam
 * (`db/constraints.ts`) and the compound unique keys `pages (site, slug)` and
 * `redirects (site, from)` are emitted by drizzle. One generated line is hand-corrected:
 * drizzle-kit drops `sources` (CASCADE, which takes the foreign keys pointing at it) before it
 * drops those three foreign keys by name, so their `DROP CONSTRAINT` carries `IF EXISTS`. Then
 * two hand-written steps (marked below), which drizzle-kit does not manage:
 * 1. **`payment_events` is append-only** — the trigger of
 *    `collections/payment-events/append-only.ts`, copied here so this migration never changes
 *    under a later edit of that file (`db/migrations.test.ts` holds the copy equal to it).
 * 2. **`orders_number_seq`** — an order's number comes from a database sequence (COMMERCE.md
 *    §8), from 100001, owned by `orders.number` so it goes with the column. The order code takes
 *    `nextval('orders_number_seq')`; the column has no default, so Payload's `required` still
 *    refuses an order saved without a number.
 *
 * **Rollout.** Additive except the drops of `sources` (and its versions), `works_references.ref`
 * and `source_id`, and the old `works_cataloguing_ai_draft` list, whose data the reset never
 * released; and `media.subject` is added `NOT NULL` with no default, so it applies only to a
 * database with no media rows — true of every database today (the reset's `indies_db` is
 * empty until 3.7 seeds it after this migration). A database with media would need the subject
 * backfilled first, by a hand-written step.
 */

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`SET LOCAL lock_timeout = '5s'`)
  await db.execute(sql`
   CREATE TYPE "public"."enum_users_access_changes_from_role" AS ENUM('owner', 'editor', 'store');
  CREATE TYPE "public"."enum_users_access_changes_to_role" AS ENUM('owner', 'editor', 'store');
  CREATE TYPE "public"."enum_orders_history_from" AS ENUM('pending_payment', 'paid', 'processing', 'waiting_driver', 'on_the_way', 'delivered', 'cancelled', 'expired');
  CREATE TYPE "public"."enum_orders_history_to" AS ENUM('pending_payment', 'paid', 'processing', 'waiting_driver', 'on_the_way', 'delivered', 'cancelled', 'expired');
  CREATE TYPE "public"."enum_orders_history_actor" AS ENUM('user', 'midtrans', 'system');
  CREATE TYPE "public"."enum_orders_site" AS ENUM('shop');
  CREATE TYPE "public"."enum_orders_channel" AS ENUM('web', 'replacement');
  CREATE TYPE "public"."enum_orders_contact_locale" AS ENUM('en', 'id');
  CREATE TYPE "public"."enum_orders_discount_kind" AS ENUM('percent', 'fixed');
  CREATE TYPE "public"."enum_orders_status" AS ENUM('pending_payment', 'paid', 'processing', 'waiting_driver', 'on_the_way', 'delivered', 'cancelled', 'expired');
  CREATE TYPE "public"."enum_payment_events_provider" AS ENUM('midtrans');
  CREATE TYPE "public"."enum_payment_events_source" AS ENUM('webhook', 'reconcile', 'simulate');
  CREATE TYPE "public"."enum_discounts_kind" AS ENUM('percent', 'fixed');
  CREATE TYPE "public"."enum_products_site" AS ENUM('shop');
  CREATE TYPE "public"."enum_products_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_products_translation_status" AS ENUM('entered', 'machine', 'reviewed');
  CREATE TYPE "public"."enum__products_v_version_site" AS ENUM('shop');
  CREATE TYPE "public"."enum__products_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__products_v_published_locale" AS ENUM('en', 'id');
  CREATE TYPE "public"."enum__products_v_version_translation_status" AS ENUM('entered', 'machine', 'reviewed');
  CREATE TYPE "public"."work_status_vocabulary" AS ENUM('available', 'on-hold', 'sold');
  CREATE TYPE "public"."enum_works_location" AS ENUM('singapore', 'jakarta');
  CREATE TYPE "public"."enum__works_v_version_location" AS ENUM('singapore', 'jakarta');
  CREATE TYPE "public"."enum_media_subject" AS ENUM('work', 'product', 'store', 'other');
  CREATE TYPE "public"."enum_pages_site" AS ENUM('gallery', 'shop');
  CREATE TYPE "public"."enum_pages_kind" AS ENUM('page', 'story', 'collection');
  CREATE TYPE "public"."enum_pages_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__pages_v_version_site" AS ENUM('gallery', 'shop');
  CREATE TYPE "public"."enum__pages_v_version_kind" AS ENUM('page', 'story', 'collection');
  CREATE TYPE "public"."enum__pages_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__pages_v_published_locale" AS ENUM('en', 'id');
  CREATE TYPE "public"."enum_redirects_site" AS ENUM('gallery', 'shop');
  CREATE TYPE "public"."enum_redirects_code" AS ENUM('301', '302');
  CREATE TYPE "public"."enum_redirects_source" AS ENUM('legacy', 'editor', 'slug-change');
  CREATE TYPE "public"."enum_leads_status_history_status" AS ENUM('new', 'contacted', 'in_progress', 'closed', 'spam');
  CREATE TYPE "public"."enum_leads_kind" AS ENUM('ask', 'sell', 'partnership', 'contact', 'chat');
  CREATE TYPE "public"."enum_leads_site" AS ENUM('gallery', 'shop');
  CREATE TYPE "public"."enum_leads_source" AS ENUM('chat', 'form', 'page');
  CREATE TYPE "public"."enum_leads_payload_preferred_channel" AS ENUM('whatsapp', 'email');
  CREATE TYPE "public"."enum_leads_payload_locale" AS ENUM('en', 'id');
  CREATE TYPE "public"."enum_leads_status" AS ENUM('new', 'contacted', 'in_progress', 'closed', 'spam');
  CREATE TYPE "public"."enum_partners_kind" AS ENUM('hotel', 'shop', 'restaurant', 'other');
  CREATE TYPE "public"."enum_partners_site" AS ENUM('gallery', 'shop');
  CREATE TYPE "public"."enum_partners_status" AS ENUM('prospect', 'active', 'paused', 'ended');
  CREATE TYPE "public"."enum_chat_sessions_transcript_role" AS ENUM('user', 'assistant');
  CREATE TYPE "public"."enum_chat_sessions_site" AS ENUM('gallery', 'shop');
  CREATE TYPE "public"."enum_chat_sessions_locale" AS ENUM('en', 'id');
  CREATE TYPE "public"."enum_chat_sessions_outcome" AS ENUM('refused', 'blocked', 'handoff', 'lead');
  CREATE TYPE "public"."enum_events_site" AS ENUM('gallery', 'shop');
  CREATE TYPE "public"."enum_events_name" AS ENUM('page.viewed', 'search.submitted', 'listing.viewed', 'item.viewed', 'item.zoomed', 'product.viewed', 'ask.clicked', 'sell.clicked', 'partnership.clicked', 'lead.created', 'chat.started', 'chat.handedOff', 'chat.leadCreated', 'cart.added', 'cart.removed', 'checkout.started', 'checkout.stepCompleted', 'checkout.blocked', 'payment.opened', 'order.created', 'order.paid', 'order.statusChanged', 'tracking.viewed', 'vitals.reported');
  CREATE TYPE "public"."enum_events_source" AS ENUM('beacon', 'server');
  CREATE TYPE "public"."enum_events_device_class" AS ENUM('mobile', 'tablet', 'desktop');
  CREATE TYPE "public"."enum_events_locale" AS ENUM('en', 'id');
  CREATE TABLE "users_access_changes" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"at" timestamp(3) with time zone NOT NULL,
  	"by_id" integer,
  	"from_role" "enum_users_access_changes_from_role",
  	"to_role" "enum_users_access_changes_to_role" NOT NULL,
  	"from_store_id" integer,
  	"to_store_id" integer
  );
  
  CREATE TABLE "stores_images" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer NOT NULL
  );
  
  CREATE TABLE "stores_locales" (
  	"hours" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "stock_levels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"store_id" integer NOT NULL,
  	"product_id" integer NOT NULL,
  	"variant_sku" varchar,
  	"quantity" numeric DEFAULT 0 NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	CONSTRAINT "stock_levels_store_product_variant_unique" UNIQUE NULLS NOT DISTINCT("store_id","product_id","variant_sku"),
  	CONSTRAINT "stock_levels_quantity_non_negative" CHECK (quantity IS NOT NULL AND quantity >= 0 AND quantity = trunc(quantity)),
  	CONSTRAINT "stock_levels_variant_sku_not_blank" CHECK (variant_sku IS NULL OR btrim(variant_sku) <> '')
  );
  
  CREATE TABLE "orders_lines" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"product_id" integer NOT NULL,
  	"variant_sku" varchar,
  	"sku" varchar NOT NULL,
  	"name" varchar NOT NULL,
  	"variant_label" varchar,
  	"unit_price" numeric NOT NULL,
  	"qty" numeric NOT NULL,
  	"line_total" numeric NOT NULL,
  	"image_id" integer,
  	CONSTRAINT "orders_lines_priced" CHECK (qty IS NOT NULL AND qty >= 1 AND qty = trunc(qty) AND unit_price IS NOT NULL AND unit_price >= 0 AND unit_price = trunc(unit_price) AND line_total IS NOT NULL AND line_total = unit_price * qty)
  );
  
  CREATE TABLE "orders_history" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"from" "enum_orders_history_from",
  	"to" "enum_orders_history_to" NOT NULL,
  	"at" timestamp(3) with time zone NOT NULL,
  	"actor" "enum_orders_history_actor" DEFAULT 'user' NOT NULL,
  	"by_id" integer,
  	"note" varchar
  );
  
  CREATE TABLE "orders_payment_attempts" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"midtrans_order_id" varchar NOT NULL,
  	"snap_token" varchar,
  	"created_at" timestamp(3) with time zone NOT NULL,
  	"state" varchar
  );
  
  CREATE TABLE "orders" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"number" numeric NOT NULL,
  	"site" "enum_orders_site" DEFAULT 'shop' NOT NULL,
  	"channel" "enum_orders_channel" DEFAULT 'web' NOT NULL,
  	"replacement_of_id" integer,
  	"contact_name" varchar NOT NULL,
  	"contact_whatsapp" varchar NOT NULL,
  	"contact_email" varchar NOT NULL,
  	"contact_locale" "enum_orders_contact_locale" DEFAULT 'en' NOT NULL,
  	"delivery_address" varchar NOT NULL,
  	"delivery_notes" varchar,
  	"delivery_lat" numeric NOT NULL,
  	"delivery_lng" numeric NOT NULL,
  	"gift_note" varchar,
  	"store_id" integer NOT NULL,
  	"store_snapshot_code" varchar,
  	"store_snapshot_name" varchar,
  	"store_snapshot_area" varchar,
  	"distance_km" numeric,
  	"totals_subtotal" numeric NOT NULL,
  	"totals_discount" numeric DEFAULT 0 NOT NULL,
  	"totals_delivery_fee" numeric DEFAULT 0 NOT NULL,
  	"totals_total" numeric NOT NULL,
  	"discount_code" varchar,
  	"discount_kind" "enum_orders_discount_kind",
  	"discount_value" numeric,
  	"status" "enum_orders_status" DEFAULT 'pending_payment' NOT NULL,
  	"payment_method" varchar,
  	"payment_transaction_id" varchar,
  	"payment_paid_at" timestamp(3) with time zone,
  	"driver_image_key" varchar,
  	"driver_image_content_type" varchar,
  	"driver_image_width" numeric,
  	"driver_image_height" numeric,
  	"driver_image_uploaded_at" timestamp(3) with time zone,
  	"driver_image_uploaded_by_id" integer,
  	"tracking_token_hash" varchar NOT NULL,
  	"expires_at" timestamp(3) with time zone,
  	"needs_attention_flag" boolean DEFAULT false,
  	"needs_attention_reason" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	CONSTRAINT "orders_totals_priced" CHECK (totals_subtotal IS NOT NULL AND totals_subtotal >= 0 AND totals_discount IS NOT NULL AND totals_discount >= 0 AND totals_delivery_fee IS NOT NULL AND totals_delivery_fee >= 0 AND totals_total IS NOT NULL AND totals_total >= 0 AND totals_discount <= totals_subtotal AND totals_total = totals_subtotal - totals_discount + totals_delivery_fee),
  	CONSTRAINT "orders_totals_whole" CHECK (totals_subtotal = trunc(totals_subtotal) AND totals_discount = trunc(totals_discount) AND totals_delivery_fee = trunc(totals_delivery_fee) AND totals_total = trunc(totals_total)),
  	CONSTRAINT "orders_tracking_token_hash_shape" CHECK (tracking_token_hash ~ '^[0-9a-f]{64}$'),
  	CONSTRAINT "orders_distance_non_negative" CHECK (distance_km IS NULL OR distance_km >= 0)
  );
  
  CREATE TABLE "payment_events" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"provider" "enum_payment_events_provider" DEFAULT 'midtrans' NOT NULL,
  	"dedupe_key" varchar NOT NULL,
  	"order_id" integer,
  	"midtrans_order_id" varchar,
  	"transaction_status" varchar,
  	"fraud_status" varchar,
  	"status_code" varchar,
  	"gross_amount" numeric,
  	"source" "enum_payment_events_source" NOT NULL,
  	"outcome" varchar,
  	"payload_hash" varchar,
  	"received_at" timestamp(3) with time zone NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	CONSTRAINT "payment_events_gross_amount_whole" CHECK (gross_amount IS NULL OR (gross_amount >= 0 AND gross_amount = trunc(gross_amount))),
  	CONSTRAINT "payment_events_dedupe_key_not_blank" CHECK (btrim(dedupe_key) <> '')
  );
  
  CREATE TABLE "discounts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"code" varchar NOT NULL,
  	"kind" "enum_discounts_kind" NOT NULL,
  	"value" numeric NOT NULL,
  	"min_spend" numeric,
  	"once_per_buyer" boolean DEFAULT false,
  	"starts_at" timestamp(3) with time zone,
  	"ends_at" timestamp(3) with time zone,
  	"usage_limit" numeric,
  	"used_count" numeric DEFAULT 0 NOT NULL,
  	"active" boolean DEFAULT true,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	CONSTRAINT "discounts_code_normalised" CHECK (code = upper(btrim(code)) AND code <> ''),
  	CONSTRAINT "discounts_value_valid" CHECK (value IS NOT NULL AND value >= 1 AND value = trunc(value) AND (kind <> 'percent' OR value <= 100)),
  	CONSTRAINT "discounts_min_spend_whole" CHECK (min_spend IS NULL OR (min_spend >= 0 AND min_spend = trunc(min_spend))),
  	CONSTRAINT "discounts_usage_counted" CHECK (used_count IS NOT NULL AND used_count >= 0 AND used_count = trunc(used_count) AND (usage_limit IS NULL OR (usage_limit >= 1 AND usage_limit = trunc(usage_limit) AND used_count <= usage_limit))),
  	CONSTRAINT "discounts_window_ordered" CHECK (starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at)
  );
  
  CREATE TABLE "products_images" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer
  );
  
  CREATE TABLE "products_images_locales" (
  	"caption" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  
  CREATE TABLE "products_variants" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"sku" varchar,
  	"price" numeric,
  	"active" boolean DEFAULT true,
  	CONSTRAINT "products_variants_price_whole_rupiah" CHECK (price IS NULL OR (price >= 1 AND price = trunc(price)))
  );
  
  CREATE TABLE "products_variants_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  
  CREATE TABLE "products" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"sku" varchar,
  	"slug" varchar,
  	"category_id" integer,
  	"price" numeric,
  	"related_work_id" integer,
  	"site" "enum_products_site" DEFAULT 'shop',
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "enum_products_status" DEFAULT 'draft',
  	CONSTRAINT "products_price_whole_rupiah" CHECK (price IS NULL OR (price >= 1 AND price = trunc(price)))
  );
  
  CREATE TABLE "products_locales" (
  	"name" varchar,
  	"description" varchar,
  	"seo_title" varchar,
  	"seo_description" varchar,
  	"translation_status" "enum_products_translation_status" DEFAULT 'entered',
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "_products_v_version_images" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"image_id" integer,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_products_v_version_images_locales" (
  	"caption" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "_products_v_version_variants" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"sku" varchar,
  	"price" numeric,
  	"active" boolean DEFAULT true,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_products_v_version_variants_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "_products_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"parent_id" integer,
  	"version_sku" varchar,
  	"version_slug" varchar,
  	"version_category_id" integer,
  	"version_price" numeric,
  	"version_related_work_id" integer,
  	"version_site" "enum__products_v_version_site" DEFAULT 'shop',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "enum__products_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"snapshot" boolean,
  	"published_locale" "enum__products_v_published_locale",
  	"latest" boolean
  );
  
  CREATE TABLE "_products_v_locales" (
  	"version_name" varchar,
  	"version_description" varchar,
  	"version_seo_title" varchar,
  	"version_seo_description" varchar,
  	"version_translation_status" "enum__products_v_version_translation_status" DEFAULT 'entered',
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "pages" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"site" "enum_pages_site",
  	"kind" "enum_pages_kind",
  	"slug" varchar,
  	"hero_id" integer,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "enum_pages_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "pages_locales" (
  	"title" varchar,
  	"intro" varchar,
  	"body" varchar,
  	"seo_title" varchar,
  	"seo_description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "pages_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"works_id" integer
  );
  
  CREATE TABLE "_pages_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"parent_id" integer,
  	"version_site" "enum__pages_v_version_site",
  	"version_kind" "enum__pages_v_version_kind",
  	"version_slug" varchar,
  	"version_hero_id" integer,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "enum__pages_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"snapshot" boolean,
  	"published_locale" "enum__pages_v_published_locale",
  	"latest" boolean
  );
  
  CREATE TABLE "_pages_v_locales" (
  	"version_title" varchar,
  	"version_intro" varchar,
  	"version_body" varchar,
  	"version_seo_title" varchar,
  	"version_seo_description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "_pages_v_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"works_id" integer
  );
  
  CREATE TABLE "redirects" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"site" "enum_redirects_site" NOT NULL,
  	"from" varchar NOT NULL,
  	"to" varchar NOT NULL,
  	"code" "enum_redirects_code" DEFAULT '301' NOT NULL,
  	"source" "enum_redirects_source" NOT NULL,
  	"hits" numeric DEFAULT 0,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "leads_status_history" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"status" "enum_leads_status_history_status" NOT NULL,
  	"by_id" integer,
  	"at" timestamp(3) with time zone NOT NULL
  );
  
  CREATE TABLE "leads" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"kind" "enum_leads_kind" NOT NULL,
  	"site" "enum_leads_site" NOT NULL,
  	"source" "enum_leads_source" NOT NULL,
  	"payload_name" varchar,
  	"payload_whatsapp" varchar,
  	"payload_email" varchar,
  	"payload_preferred_channel" "enum_leads_payload_preferred_channel",
  	"payload_message" varchar,
  	"payload_locale" "enum_leads_payload_locale",
  	"payload_consent_version" varchar,
  	"payload_consent_at" timestamp(3) with time zone,
  	"chat_session_id" integer,
  	"status" "enum_leads_status" DEFAULT 'new' NOT NULL,
  	"first_reply_at" timestamp(3) with time zone,
  	"notes" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "leads_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"works_id" integer
  );
  
  CREATE TABLE "partners" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"name" varchar NOT NULL,
  	"kind" "enum_partners_kind" NOT NULL,
  	"site" "enum_partners_site" NOT NULL,
  	"contact_person" varchar,
  	"contact_whatsapp" varchar,
  	"contact_email" varchar,
  	"contact_phone" varchar,
  	"address" varchar,
  	"terms" varchar,
  	"status" "enum_partners_status" DEFAULT 'prospect' NOT NULL,
  	"notes" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "partners_texts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"text" varchar
  );
  
  CREATE TABLE "chat_sessions_transcript" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"role" "enum_chat_sessions_transcript_role" NOT NULL,
  	"at" timestamp(3) with time zone NOT NULL,
  	"text" varchar NOT NULL
  );
  
  CREATE TABLE "chat_sessions" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"site" "enum_chat_sessions_site" NOT NULL,
  	"locale" "enum_chat_sessions_locale" NOT NULL,
  	"started_at" timestamp(3) with time zone NOT NULL,
  	"last_message_at" timestamp(3) with time zone NOT NULL,
  	"ip_hash" varchar,
  	"usage_input_tokens" numeric,
  	"usage_output_tokens" numeric,
  	"usage_cost_usd" numeric,
  	"outcome" "enum_chat_sessions_outcome",
  	"lead_id" integer,
  	"expires_at" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "chat_sessions_texts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"text" varchar
  );
  
  CREATE TABLE "chat_sessions_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"works_id" integer
  );
  
  CREATE TABLE "events" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"site" "enum_events_site" NOT NULL,
  	"name" "enum_events_name" NOT NULL,
  	"at" timestamp(3) with time zone NOT NULL,
  	"path" varchar,
  	"ref" varchar,
  	"props" jsonb,
  	"day" varchar NOT NULL,
  	"source" "enum_events_source" NOT NULL,
  	"session_id" varchar,
  	"device_class" "enum_events_device_class",
  	"locale" "enum_events_locale",
  	"referrer_host" varchar,
  	"utm_source" varchar,
  	"utm_medium" varchar,
  	"utm_campaign" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "site_settings_gallery_social" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"platform" varchar NOT NULL,
  	"url" varchar NOT NULL
  );
  
  CREATE TABLE "site_settings_shop_social" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"platform" varchar NOT NULL,
  	"url" varchar NOT NULL
  );
  
  CREATE TABLE "site_settings_shop_delivery_bands" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"up_to_km" numeric NOT NULL,
  	"fee_idr" numeric NOT NULL
  );
  
  CREATE TABLE "site_settings" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"gallery_contact_whatsapp" varchar,
  	"gallery_contact_email" varchar,
  	"gallery_contact_phone" varchar,
  	"gallery_ai_chat_enabled" boolean DEFAULT false,
  	"gallery_ai_drafting_enabled" boolean DEFAULT false,
  	"gallery_ai_daily_budget_usd" numeric DEFAULT 5,
  	"gallery_ai_session_token_cap" numeric DEFAULT 150000,
  	"shop_contact_whatsapp" varchar,
  	"shop_contact_email" varchar,
  	"shop_contact_phone" varchar,
  	"shop_ai_chat_enabled" boolean DEFAULT false,
  	"shop_ai_drafting_enabled" boolean DEFAULT false,
  	"shop_ai_daily_budget_usd" numeric DEFAULT 5,
  	"shop_ai_session_token_cap" numeric DEFAULT 150000,
  	"shop_checkout_enabled" boolean DEFAULT true,
  	"shop_delivery_free_over_idr" numeric DEFAULT 500000,
  	"shop_welcome_discount" varchar,
  	"shop_order_expiry_minutes" numeric DEFAULT 60,
  	"shop_store_alerts" boolean DEFAULT true,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "site_settings_locales" (
  	"gallery_reply_promise" varchar,
  	"gallery_hours" varchar,
  	"gallery_announcement" varchar,
  	"shop_reply_promise" varchar,
  	"shop_hours" varchar,
  	"shop_announcement" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  CREATE TABLE "site_settings_texts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"text" varchar
  );
  
  ALTER TABLE "works_cataloguing_ai_draft" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_works_v_version_cataloguing_ai_draft" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "sources" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_sources_v" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "works_cataloguing_ai_draft" CASCADE;
  DROP TABLE "_works_v_version_cataloguing_ai_draft" CASCADE;
  DROP TABLE "sources" CASCADE;
  DROP TABLE "_sources_v" CASCADE;
  ALTER TABLE "works_references" DROP CONSTRAINT IF EXISTS "works_references_source_id_sources_id_fk";
  
  ALTER TABLE "_works_v_version_references" DROP CONSTRAINT IF EXISTS "_works_v_version_references_source_id_sources_id_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_sources_fk";
  
  DROP INDEX "works_references_source_idx";
  DROP INDEX "_works_v_version_references_source_idx";
  DROP INDEX "payload_locked_documents_rels_sources_id_idx";
  ALTER TABLE "stores" ADD COLUMN "area" varchar;
  ALTER TABLE "stores" ADD COLUMN "address" varchar;
  ALTER TABLE "stores" ADD COLUMN "lat" numeric;
  ALTER TABLE "stores" ADD COLUMN "lng" numeric;
  ALTER TABLE "stores" ADD COLUMN "whatsapp" varchar;
  ALTER TABLE "stores" ADD COLUMN "active" boolean DEFAULT false;
  ALTER TABLE "stores" ADD COLUMN "listed" boolean DEFAULT true;
  ALTER TABLE "stores" ADD COLUMN "notes" varchar;
  ALTER TABLE "works_references" ADD COLUMN "citation" varchar;
  ALTER TABLE "works" ADD COLUMN "public_id" numeric;
  ALTER TABLE "works" ADD COLUMN "status" "work_status_vocabulary" DEFAULT 'available';
  ALTER TABLE "works" ADD COLUMN "location" "enum_works_location";
  ALTER TABLE "works" ADD COLUMN "asking_price" numeric;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_title_drafted" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_title_verified_by_id" integer;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_title_verified_at" timestamp(3) with time zone;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_description_drafted" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_description_verified_by_id" integer;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_description_verified_at" timestamp(3) with time zone;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_object_type_drafted" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_object_type_verified_by_id" integer;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_object_type_verified_at" timestamp(3) with time zone;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_date_drafted" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_date_verified_by_id" integer;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_date_verified_at" timestamp(3) with time zone;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_places_drafted" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_places_verified_by_id" integer;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_places_verified_at" timestamp(3) with time zone;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_subjects_drafted" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_subjects_verified_by_id" integer;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_subjects_verified_at" timestamp(3) with time zone;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_dimensions_drafted" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_dimensions_verified_by_id" integer;
  ALTER TABLE "works" ADD COLUMN "cataloguing_ai_draft_dimensions_verified_at" timestamp(3) with time zone;
  ALTER TABLE "_works_v_version_references" ADD COLUMN "citation" varchar;
  ALTER TABLE "_works_v" ADD COLUMN "version_public_id" numeric;
  ALTER TABLE "_works_v" ADD COLUMN "version_status" "work_status_vocabulary" DEFAULT 'available';
  ALTER TABLE "_works_v" ADD COLUMN "version_location" "enum__works_v_version_location";
  ALTER TABLE "_works_v" ADD COLUMN "version_asking_price" numeric;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_title_drafted" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_title_verified_by_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_title_verified_at" timestamp(3) with time zone;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_description_drafted" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_description_verified_by_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_description_verified_at" timestamp(3) with time zone;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_object_type_drafted" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_object_type_verified_by_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_object_type_verified_at" timestamp(3) with time zone;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_date_drafted" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_date_verified_by_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_date_verified_at" timestamp(3) with time zone;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_places_drafted" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_places_verified_by_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_places_verified_at" timestamp(3) with time zone;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_subjects_drafted" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_subjects_verified_by_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_subjects_verified_at" timestamp(3) with time zone;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_dimensions_drafted" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_dimensions_verified_by_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_cataloguing_ai_draft_dimensions_verified_at" timestamp(3) with time zone;
  ALTER TABLE "media" ADD COLUMN "subject" "enum_media_subject" NOT NULL;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "stock_levels_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "orders_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "payment_events_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "discounts_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "products_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "pages_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "redirects_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "leads_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "partners_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "chat_sessions_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "events_id" integer;
  ALTER TABLE "users_access_changes" ADD CONSTRAINT "users_access_changes_by_id_users_id_fk" FOREIGN KEY ("by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "users_access_changes" ADD CONSTRAINT "users_access_changes_from_store_id_stores_id_fk" FOREIGN KEY ("from_store_id") REFERENCES "public"."stores"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "users_access_changes" ADD CONSTRAINT "users_access_changes_to_store_id_stores_id_fk" FOREIGN KEY ("to_store_id") REFERENCES "public"."stores"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "users_access_changes" ADD CONSTRAINT "users_access_changes_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "stores_images" ADD CONSTRAINT "stores_images_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "stores_images" ADD CONSTRAINT "stores_images_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."stores"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "stores_locales" ADD CONSTRAINT "stores_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."stores"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "stock_levels" ADD CONSTRAINT "stock_levels_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "stock_levels" ADD CONSTRAINT "stock_levels_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "orders_lines" ADD CONSTRAINT "orders_lines_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "orders_lines" ADD CONSTRAINT "orders_lines_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "orders_lines" ADD CONSTRAINT "orders_lines_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "orders_history" ADD CONSTRAINT "orders_history_by_id_users_id_fk" FOREIGN KEY ("by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "orders_history" ADD CONSTRAINT "orders_history_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "orders_payment_attempts" ADD CONSTRAINT "orders_payment_attempts_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "orders" ADD CONSTRAINT "orders_replacement_of_id_orders_id_fk" FOREIGN KEY ("replacement_of_id") REFERENCES "public"."orders"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "orders" ADD CONSTRAINT "orders_store_id_stores_id_fk" FOREIGN KEY ("store_id") REFERENCES "public"."stores"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "orders" ADD CONSTRAINT "orders_driver_image_uploaded_by_id_users_id_fk" FOREIGN KEY ("driver_image_uploaded_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payment_events" ADD CONSTRAINT "payment_events_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "products_images" ADD CONSTRAINT "products_images_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "products_images" ADD CONSTRAINT "products_images_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "products_images_locales" ADD CONSTRAINT "products_images_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."products_images"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "products_variants" ADD CONSTRAINT "products_variants_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "products_variants_locales" ADD CONSTRAINT "products_variants_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."products_variants"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "products" ADD CONSTRAINT "products_category_id_terms_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."terms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "products" ADD CONSTRAINT "products_related_work_id_works_id_fk" FOREIGN KEY ("related_work_id") REFERENCES "public"."works"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "products_locales" ADD CONSTRAINT "products_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_products_v_version_images" ADD CONSTRAINT "_products_v_version_images_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_products_v_version_images" ADD CONSTRAINT "_products_v_version_images_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_products_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_products_v_version_images_locales" ADD CONSTRAINT "_products_v_version_images_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_products_v_version_images"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_products_v_version_variants" ADD CONSTRAINT "_products_v_version_variants_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_products_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_products_v_version_variants_locales" ADD CONSTRAINT "_products_v_version_variants_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_products_v_version_variants"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_products_v" ADD CONSTRAINT "_products_v_parent_id_products_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."products"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_products_v" ADD CONSTRAINT "_products_v_version_category_id_terms_id_fk" FOREIGN KEY ("version_category_id") REFERENCES "public"."terms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_products_v" ADD CONSTRAINT "_products_v_version_related_work_id_works_id_fk" FOREIGN KEY ("version_related_work_id") REFERENCES "public"."works"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_products_v_locales" ADD CONSTRAINT "_products_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_products_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pages" ADD CONSTRAINT "pages_hero_id_media_id_fk" FOREIGN KEY ("hero_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_locales" ADD CONSTRAINT "pages_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_works_fk" FOREIGN KEY ("works_id") REFERENCES "public"."works"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v" ADD CONSTRAINT "_pages_v_parent_id_pages_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."pages"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v" ADD CONSTRAINT "_pages_v_version_hero_id_media_id_fk" FOREIGN KEY ("version_hero_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_locales" ADD CONSTRAINT "_pages_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_rels" ADD CONSTRAINT "_pages_v_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_rels" ADD CONSTRAINT "_pages_v_rels_works_fk" FOREIGN KEY ("works_id") REFERENCES "public"."works"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "leads_status_history" ADD CONSTRAINT "leads_status_history_by_id_users_id_fk" FOREIGN KEY ("by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "leads_status_history" ADD CONSTRAINT "leads_status_history_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."leads"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "leads" ADD CONSTRAINT "leads_chat_session_id_chat_sessions_id_fk" FOREIGN KEY ("chat_session_id") REFERENCES "public"."chat_sessions"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "leads_rels" ADD CONSTRAINT "leads_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."leads"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "leads_rels" ADD CONSTRAINT "leads_rels_works_fk" FOREIGN KEY ("works_id") REFERENCES "public"."works"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "partners_texts" ADD CONSTRAINT "partners_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."partners"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "chat_sessions_transcript" ADD CONSTRAINT "chat_sessions_transcript_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."chat_sessions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "chat_sessions" ADD CONSTRAINT "chat_sessions_lead_id_leads_id_fk" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "chat_sessions_texts" ADD CONSTRAINT "chat_sessions_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."chat_sessions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "chat_sessions_rels" ADD CONSTRAINT "chat_sessions_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."chat_sessions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "chat_sessions_rels" ADD CONSTRAINT "chat_sessions_rels_works_fk" FOREIGN KEY ("works_id") REFERENCES "public"."works"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_settings_gallery_social" ADD CONSTRAINT "site_settings_gallery_social_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_settings"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_settings_shop_social" ADD CONSTRAINT "site_settings_shop_social_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_settings"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_settings_shop_delivery_bands" ADD CONSTRAINT "site_settings_shop_delivery_bands_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_settings"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_settings_locales" ADD CONSTRAINT "site_settings_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_settings"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_settings_texts" ADD CONSTRAINT "site_settings_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."site_settings"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "users_access_changes_order_idx" ON "users_access_changes" USING btree ("_order");
  CREATE INDEX "users_access_changes_parent_id_idx" ON "users_access_changes" USING btree ("_parent_id");
  CREATE INDEX "users_access_changes_by_idx" ON "users_access_changes" USING btree ("by_id");
  CREATE INDEX "users_access_changes_from_store_idx" ON "users_access_changes" USING btree ("from_store_id");
  CREATE INDEX "users_access_changes_to_store_idx" ON "users_access_changes" USING btree ("to_store_id");
  CREATE INDEX "stores_images_order_idx" ON "stores_images" USING btree ("_order");
  CREATE INDEX "stores_images_parent_id_idx" ON "stores_images" USING btree ("_parent_id");
  CREATE INDEX "stores_images_image_idx" ON "stores_images" USING btree ("image_id");
  CREATE UNIQUE INDEX "stores_locales_locale_parent_id_unique" ON "stores_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "stock_levels_store_idx" ON "stock_levels" USING btree ("store_id");
  CREATE INDEX "stock_levels_product_idx" ON "stock_levels" USING btree ("product_id");
  CREATE INDEX "stock_levels_updated_at_idx" ON "stock_levels" USING btree ("updated_at");
  CREATE INDEX "stock_levels_created_at_idx" ON "stock_levels" USING btree ("created_at");
  CREATE INDEX "orders_lines_order_idx" ON "orders_lines" USING btree ("_order");
  CREATE INDEX "orders_lines_parent_id_idx" ON "orders_lines" USING btree ("_parent_id");
  CREATE INDEX "orders_lines_product_idx" ON "orders_lines" USING btree ("product_id");
  CREATE INDEX "orders_lines_image_idx" ON "orders_lines" USING btree ("image_id");
  CREATE INDEX "orders_history_order_idx" ON "orders_history" USING btree ("_order");
  CREATE INDEX "orders_history_parent_id_idx" ON "orders_history" USING btree ("_parent_id");
  CREATE INDEX "orders_history_by_idx" ON "orders_history" USING btree ("by_id");
  CREATE INDEX "orders_payment_attempts_order_idx" ON "orders_payment_attempts" USING btree ("_order");
  CREATE INDEX "orders_payment_attempts_parent_id_idx" ON "orders_payment_attempts" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "orders_number_idx" ON "orders" USING btree ("number");
  CREATE INDEX "orders_replacement_of_idx" ON "orders" USING btree ("replacement_of_id");
  CREATE INDEX "orders_store_idx" ON "orders" USING btree ("store_id");
  CREATE INDEX "orders_status_idx" ON "orders" USING btree ("status");
  CREATE INDEX "orders_driver_image_driver_image_uploaded_by_idx" ON "orders" USING btree ("driver_image_uploaded_by_id");
  CREATE UNIQUE INDEX "orders_tracking_token_hash_idx" ON "orders" USING btree ("tracking_token_hash");
  CREATE INDEX "orders_updated_at_idx" ON "orders" USING btree ("updated_at");
  CREATE INDEX "orders_created_at_idx" ON "orders" USING btree ("created_at");
  CREATE UNIQUE INDEX "payment_events_dedupe_key_idx" ON "payment_events" USING btree ("dedupe_key");
  CREATE INDEX "payment_events_order_idx" ON "payment_events" USING btree ("order_id");
  CREATE INDEX "payment_events_received_at_idx" ON "payment_events" USING btree ("received_at");
  CREATE INDEX "payment_events_updated_at_idx" ON "payment_events" USING btree ("updated_at");
  CREATE INDEX "payment_events_created_at_idx" ON "payment_events" USING btree ("created_at");
  CREATE UNIQUE INDEX "discounts_code_idx" ON "discounts" USING btree ("code");
  CREATE INDEX "discounts_updated_at_idx" ON "discounts" USING btree ("updated_at");
  CREATE INDEX "discounts_created_at_idx" ON "discounts" USING btree ("created_at");
  CREATE INDEX "products_images_order_idx" ON "products_images" USING btree ("_order");
  CREATE INDEX "products_images_parent_id_idx" ON "products_images" USING btree ("_parent_id");
  CREATE INDEX "products_images_image_idx" ON "products_images" USING btree ("image_id");
  CREATE UNIQUE INDEX "products_images_locales_locale_parent_id_unique" ON "products_images_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "products_variants_order_idx" ON "products_variants" USING btree ("_order");
  CREATE INDEX "products_variants_parent_id_idx" ON "products_variants" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "products_variants_sku_idx" ON "products_variants" USING btree ("sku");
  CREATE UNIQUE INDEX "products_variants_locales_locale_parent_id_unique" ON "products_variants_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "products_sku_idx" ON "products" USING btree ("sku");
  CREATE UNIQUE INDEX "products_slug_idx" ON "products" USING btree ("slug");
  CREATE INDEX "products_category_idx" ON "products" USING btree ("category_id");
  CREATE INDEX "products_related_work_idx" ON "products" USING btree ("related_work_id");
  CREATE INDEX "products_updated_at_idx" ON "products" USING btree ("updated_at");
  CREATE INDEX "products_created_at_idx" ON "products" USING btree ("created_at");
  CREATE INDEX "products__status_idx" ON "products" USING btree ("_status");
  CREATE UNIQUE INDEX "products_locales_locale_parent_id_unique" ON "products_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_products_v_version_images_order_idx" ON "_products_v_version_images" USING btree ("_order");
  CREATE INDEX "_products_v_version_images_parent_id_idx" ON "_products_v_version_images" USING btree ("_parent_id");
  CREATE INDEX "_products_v_version_images_image_idx" ON "_products_v_version_images" USING btree ("image_id");
  CREATE UNIQUE INDEX "_products_v_version_images_locales_locale_parent_id_unique" ON "_products_v_version_images_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_products_v_version_variants_order_idx" ON "_products_v_version_variants" USING btree ("_order");
  CREATE INDEX "_products_v_version_variants_parent_id_idx" ON "_products_v_version_variants" USING btree ("_parent_id");
  CREATE INDEX "_products_v_version_variants_sku_idx" ON "_products_v_version_variants" USING btree ("sku");
  CREATE UNIQUE INDEX "_products_v_version_variants_locales_locale_parent_id_unique" ON "_products_v_version_variants_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_products_v_parent_idx" ON "_products_v" USING btree ("parent_id");
  CREATE INDEX "_products_v_version_version_sku_idx" ON "_products_v" USING btree ("version_sku");
  CREATE INDEX "_products_v_version_version_slug_idx" ON "_products_v" USING btree ("version_slug");
  CREATE INDEX "_products_v_version_version_category_idx" ON "_products_v" USING btree ("version_category_id");
  CREATE INDEX "_products_v_version_version_related_work_idx" ON "_products_v" USING btree ("version_related_work_id");
  CREATE INDEX "_products_v_version_version_updated_at_idx" ON "_products_v" USING btree ("version_updated_at");
  CREATE INDEX "_products_v_version_version_created_at_idx" ON "_products_v" USING btree ("version_created_at");
  CREATE INDEX "_products_v_version_version__status_idx" ON "_products_v" USING btree ("version__status");
  CREATE INDEX "_products_v_created_at_idx" ON "_products_v" USING btree ("created_at");
  CREATE INDEX "_products_v_updated_at_idx" ON "_products_v" USING btree ("updated_at");
  CREATE INDEX "_products_v_snapshot_idx" ON "_products_v" USING btree ("snapshot");
  CREATE INDEX "_products_v_published_locale_idx" ON "_products_v" USING btree ("published_locale");
  CREATE INDEX "_products_v_latest_idx" ON "_products_v" USING btree ("latest");
  CREATE UNIQUE INDEX "_products_v_locales_locale_parent_id_unique" ON "_products_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_hero_idx" ON "pages" USING btree ("hero_id");
  CREATE INDEX "pages_updated_at_idx" ON "pages" USING btree ("updated_at");
  CREATE INDEX "pages_created_at_idx" ON "pages" USING btree ("created_at");
  CREATE INDEX "pages__status_idx" ON "pages" USING btree ("_status");
  CREATE UNIQUE INDEX "site_slug_idx" ON "pages" USING btree ("site","slug");
  CREATE UNIQUE INDEX "pages_locales_locale_parent_id_unique" ON "pages_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "pages_rels_order_idx" ON "pages_rels" USING btree ("order");
  CREATE INDEX "pages_rels_parent_idx" ON "pages_rels" USING btree ("parent_id");
  CREATE INDEX "pages_rels_path_idx" ON "pages_rels" USING btree ("path");
  CREATE INDEX "pages_rels_works_id_idx" ON "pages_rels" USING btree ("works_id");
  CREATE INDEX "_pages_v_parent_idx" ON "_pages_v" USING btree ("parent_id");
  CREATE INDEX "_pages_v_version_version_hero_idx" ON "_pages_v" USING btree ("version_hero_id");
  CREATE INDEX "_pages_v_version_version_updated_at_idx" ON "_pages_v" USING btree ("version_updated_at");
  CREATE INDEX "_pages_v_version_version_created_at_idx" ON "_pages_v" USING btree ("version_created_at");
  CREATE INDEX "_pages_v_version_version__status_idx" ON "_pages_v" USING btree ("version__status");
  CREATE INDEX "_pages_v_created_at_idx" ON "_pages_v" USING btree ("created_at");
  CREATE INDEX "_pages_v_updated_at_idx" ON "_pages_v" USING btree ("updated_at");
  CREATE INDEX "_pages_v_snapshot_idx" ON "_pages_v" USING btree ("snapshot");
  CREATE INDEX "_pages_v_published_locale_idx" ON "_pages_v" USING btree ("published_locale");
  CREATE INDEX "_pages_v_latest_idx" ON "_pages_v" USING btree ("latest");
  CREATE INDEX "version_site_version_slug_idx" ON "_pages_v" USING btree ("version_site","version_slug");
  CREATE UNIQUE INDEX "_pages_v_locales_locale_parent_id_unique" ON "_pages_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_pages_v_rels_order_idx" ON "_pages_v_rels" USING btree ("order");
  CREATE INDEX "_pages_v_rels_parent_idx" ON "_pages_v_rels" USING btree ("parent_id");
  CREATE INDEX "_pages_v_rels_path_idx" ON "_pages_v_rels" USING btree ("path");
  CREATE INDEX "_pages_v_rels_works_id_idx" ON "_pages_v_rels" USING btree ("works_id");
  CREATE INDEX "redirects_updated_at_idx" ON "redirects" USING btree ("updated_at");
  CREATE INDEX "redirects_created_at_idx" ON "redirects" USING btree ("created_at");
  CREATE UNIQUE INDEX "site_from_idx" ON "redirects" USING btree ("site","from");
  CREATE INDEX "leads_status_history_order_idx" ON "leads_status_history" USING btree ("_order");
  CREATE INDEX "leads_status_history_parent_id_idx" ON "leads_status_history" USING btree ("_parent_id");
  CREATE INDEX "leads_status_history_by_idx" ON "leads_status_history" USING btree ("by_id");
  CREATE INDEX "leads_chat_session_idx" ON "leads" USING btree ("chat_session_id");
  CREATE INDEX "leads_updated_at_idx" ON "leads" USING btree ("updated_at");
  CREATE INDEX "leads_created_at_idx" ON "leads" USING btree ("created_at");
  CREATE INDEX "leads_rels_order_idx" ON "leads_rels" USING btree ("order");
  CREATE INDEX "leads_rels_parent_idx" ON "leads_rels" USING btree ("parent_id");
  CREATE INDEX "leads_rels_path_idx" ON "leads_rels" USING btree ("path");
  CREATE INDEX "leads_rels_works_id_idx" ON "leads_rels" USING btree ("works_id");
  CREATE INDEX "partners_updated_at_idx" ON "partners" USING btree ("updated_at");
  CREATE INDEX "partners_created_at_idx" ON "partners" USING btree ("created_at");
  CREATE INDEX "partners_texts_order_parent" ON "partners_texts" USING btree ("order","parent_id");
  CREATE INDEX "chat_sessions_transcript_order_idx" ON "chat_sessions_transcript" USING btree ("_order");
  CREATE INDEX "chat_sessions_transcript_parent_id_idx" ON "chat_sessions_transcript" USING btree ("_parent_id");
  CREATE INDEX "chat_sessions_lead_idx" ON "chat_sessions" USING btree ("lead_id");
  CREATE INDEX "chat_sessions_updated_at_idx" ON "chat_sessions" USING btree ("updated_at");
  CREATE INDEX "chat_sessions_created_at_idx" ON "chat_sessions" USING btree ("created_at");
  CREATE INDEX "chat_sessions_texts_order_parent" ON "chat_sessions_texts" USING btree ("order","parent_id");
  CREATE INDEX "chat_sessions_rels_order_idx" ON "chat_sessions_rels" USING btree ("order");
  CREATE INDEX "chat_sessions_rels_parent_idx" ON "chat_sessions_rels" USING btree ("parent_id");
  CREATE INDEX "chat_sessions_rels_path_idx" ON "chat_sessions_rels" USING btree ("path");
  CREATE INDEX "chat_sessions_rels_works_id_idx" ON "chat_sessions_rels" USING btree ("works_id");
  CREATE INDEX "events_site_idx" ON "events" USING btree ("site");
  CREATE INDEX "events_name_idx" ON "events" USING btree ("name");
  CREATE INDEX "events_at_idx" ON "events" USING btree ("at");
  CREATE INDEX "events_day_idx" ON "events" USING btree ("day");
  CREATE INDEX "events_session_id_idx" ON "events" USING btree ("session_id");
  CREATE INDEX "events_updated_at_idx" ON "events" USING btree ("updated_at");
  CREATE INDEX "events_created_at_idx" ON "events" USING btree ("created_at");
  CREATE INDEX "site_name_at_idx" ON "events" USING btree ("site","name","at");
  CREATE INDEX "sessionId_idx" ON "events" USING btree ("session_id");
  CREATE INDEX "site_day_name_idx" ON "events" USING btree ("site","day","name");
  CREATE INDEX "site_settings_gallery_social_order_idx" ON "site_settings_gallery_social" USING btree ("_order");
  CREATE INDEX "site_settings_gallery_social_parent_id_idx" ON "site_settings_gallery_social" USING btree ("_parent_id");
  CREATE INDEX "site_settings_shop_social_order_idx" ON "site_settings_shop_social" USING btree ("_order");
  CREATE INDEX "site_settings_shop_social_parent_id_idx" ON "site_settings_shop_social" USING btree ("_parent_id");
  CREATE INDEX "site_settings_shop_delivery_bands_order_idx" ON "site_settings_shop_delivery_bands" USING btree ("_order");
  CREATE INDEX "site_settings_shop_delivery_bands_parent_id_idx" ON "site_settings_shop_delivery_bands" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "site_settings_locales_locale_parent_id_unique" ON "site_settings_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "site_settings_texts_order_parent" ON "site_settings_texts" USING btree ("order","parent_id");
  ALTER TABLE "works" ADD CONSTRAINT "works_cataloguing_ai_draft_title_verified_by_id_users_id_fk" FOREIGN KEY ("cataloguing_ai_draft_title_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "works" ADD CONSTRAINT "works_cataloguing_ai_draft_description_verified_by_id_users_id_fk" FOREIGN KEY ("cataloguing_ai_draft_description_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "works" ADD CONSTRAINT "works_cataloguing_ai_draft_object_type_verified_by_id_users_id_fk" FOREIGN KEY ("cataloguing_ai_draft_object_type_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "works" ADD CONSTRAINT "works_cataloguing_ai_draft_date_verified_by_id_users_id_fk" FOREIGN KEY ("cataloguing_ai_draft_date_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "works" ADD CONSTRAINT "works_cataloguing_ai_draft_places_verified_by_id_users_id_fk" FOREIGN KEY ("cataloguing_ai_draft_places_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "works" ADD CONSTRAINT "works_cataloguing_ai_draft_subjects_verified_by_id_users_id_fk" FOREIGN KEY ("cataloguing_ai_draft_subjects_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "works" ADD CONSTRAINT "works_cataloguing_ai_draft_dimensions_verified_by_id_users_id_fk" FOREIGN KEY ("cataloguing_ai_draft_dimensions_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_cataloguing_ai_draft_title_verified_by_id_users_id_fk" FOREIGN KEY ("version_cataloguing_ai_draft_title_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_cataloguing_ai_draft_description_verified_by_id_users_id_fk" FOREIGN KEY ("version_cataloguing_ai_draft_description_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_cataloguing_ai_draft_object_type_verified_by_id_users_id_fk" FOREIGN KEY ("version_cataloguing_ai_draft_object_type_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_cataloguing_ai_draft_date_verified_by_id_users_id_fk" FOREIGN KEY ("version_cataloguing_ai_draft_date_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_cataloguing_ai_draft_places_verified_by_id_users_id_fk" FOREIGN KEY ("version_cataloguing_ai_draft_places_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_cataloguing_ai_draft_subjects_verified_by_id_users_id_fk" FOREIGN KEY ("version_cataloguing_ai_draft_subjects_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_cataloguing_ai_draft_dimensions_verified_by_id_users_id_fk" FOREIGN KEY ("version_cataloguing_ai_draft_dimensions_verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_stock_levels_fk" FOREIGN KEY ("stock_levels_id") REFERENCES "public"."stock_levels"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_orders_fk" FOREIGN KEY ("orders_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_payment_events_fk" FOREIGN KEY ("payment_events_id") REFERENCES "public"."payment_events"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_discounts_fk" FOREIGN KEY ("discounts_id") REFERENCES "public"."discounts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_products_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_redirects_fk" FOREIGN KEY ("redirects_id") REFERENCES "public"."redirects"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_leads_fk" FOREIGN KEY ("leads_id") REFERENCES "public"."leads"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_partners_fk" FOREIGN KEY ("partners_id") REFERENCES "public"."partners"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_chat_sessions_fk" FOREIGN KEY ("chat_sessions_id") REFERENCES "public"."chat_sessions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_events_fk" FOREIGN KEY ("events_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
  CREATE UNIQUE INDEX "works_public_id_idx" ON "works" USING btree ("public_id");
  CREATE INDEX "works_status_idx" ON "works" USING btree ("status");
  CREATE INDEX "works_cataloguing_ai_draft_title_cataloguing_ai_draft_ti_idx" ON "works" USING btree ("cataloguing_ai_draft_title_verified_by_id");
  CREATE INDEX "works_cataloguing_ai_draft_description_cataloguing_ai_dr_idx" ON "works" USING btree ("cataloguing_ai_draft_description_verified_by_id");
  CREATE INDEX "works_cataloguing_ai_draft_object_type_cataloguing_ai_dr_idx" ON "works" USING btree ("cataloguing_ai_draft_object_type_verified_by_id");
  CREATE INDEX "works_cataloguing_ai_draft_date_cataloguing_ai_draft_dat_idx" ON "works" USING btree ("cataloguing_ai_draft_date_verified_by_id");
  CREATE INDEX "works_cataloguing_ai_draft_places_cataloguing_ai_draft_p_idx" ON "works" USING btree ("cataloguing_ai_draft_places_verified_by_id");
  CREATE INDEX "works_cataloguing_ai_draft_subjects_cataloguing_ai_draft_idx" ON "works" USING btree ("cataloguing_ai_draft_subjects_verified_by_id");
  CREATE INDEX "works_cataloguing_ai_draft_dimensions_cataloguing_ai_dra_idx" ON "works" USING btree ("cataloguing_ai_draft_dimensions_verified_by_id");
  CREATE INDEX "_works_v_version_version_public_id_idx" ON "_works_v" USING btree ("version_public_id");
  CREATE INDEX "_works_v_version_version_status_idx" ON "_works_v" USING btree ("version_status");
  CREATE INDEX "_works_v_version_cataloguing_ai_draft_title_version_cata_idx" ON "_works_v" USING btree ("version_cataloguing_ai_draft_title_verified_by_id");
  CREATE INDEX "_works_v_version_cataloguing_ai_draft_description_versio_idx" ON "_works_v" USING btree ("version_cataloguing_ai_draft_description_verified_by_id");
  CREATE INDEX "_works_v_version_cataloguing_ai_draft_object_type_versio_idx" ON "_works_v" USING btree ("version_cataloguing_ai_draft_object_type_verified_by_id");
  CREATE INDEX "_works_v_version_cataloguing_ai_draft_date_version_catal_idx" ON "_works_v" USING btree ("version_cataloguing_ai_draft_date_verified_by_id");
  CREATE INDEX "_works_v_version_cataloguing_ai_draft_places_version_cat_idx" ON "_works_v" USING btree ("version_cataloguing_ai_draft_places_verified_by_id");
  CREATE INDEX "_works_v_version_cataloguing_ai_draft_subjects_version_c_idx" ON "_works_v" USING btree ("version_cataloguing_ai_draft_subjects_verified_by_id");
  CREATE INDEX "_works_v_version_cataloguing_ai_draft_dimensions_version_idx" ON "_works_v" USING btree ("version_cataloguing_ai_draft_dimensions_verified_by_id");
  CREATE INDEX "payload_locked_documents_rels_stock_levels_id_idx" ON "payload_locked_documents_rels" USING btree ("stock_levels_id");
  CREATE INDEX "payload_locked_documents_rels_orders_id_idx" ON "payload_locked_documents_rels" USING btree ("orders_id");
  CREATE INDEX "payload_locked_documents_rels_payment_events_id_idx" ON "payload_locked_documents_rels" USING btree ("payment_events_id");
  CREATE INDEX "payload_locked_documents_rels_discounts_id_idx" ON "payload_locked_documents_rels" USING btree ("discounts_id");
  CREATE INDEX "payload_locked_documents_rels_products_id_idx" ON "payload_locked_documents_rels" USING btree ("products_id");
  CREATE INDEX "payload_locked_documents_rels_pages_id_idx" ON "payload_locked_documents_rels" USING btree ("pages_id");
  CREATE INDEX "payload_locked_documents_rels_redirects_id_idx" ON "payload_locked_documents_rels" USING btree ("redirects_id");
  CREATE INDEX "payload_locked_documents_rels_leads_id_idx" ON "payload_locked_documents_rels" USING btree ("leads_id");
  CREATE INDEX "payload_locked_documents_rels_partners_id_idx" ON "payload_locked_documents_rels" USING btree ("partners_id");
  CREATE INDEX "payload_locked_documents_rels_chat_sessions_id_idx" ON "payload_locked_documents_rels" USING btree ("chat_sessions_id");
  CREATE INDEX "payload_locked_documents_rels_events_id_idx" ON "payload_locked_documents_rels" USING btree ("events_id");
  ALTER TABLE "works_references" DROP COLUMN "source_id";
  ALTER TABLE "works_references" DROP COLUMN "ref";
  ALTER TABLE "_works_v_version_references" DROP COLUMN "source_id";
  ALTER TABLE "_works_v_version_references" DROP COLUMN "ref";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "sources_id";
  ALTER TABLE "users" ADD CONSTRAINT "users_store_staff_have_a_store" CHECK (role <> 'store' OR store_id IS NOT NULL);
  ALTER TABLE "stores" ADD CONSTRAINT "stores_pin_in_indonesia" CHECK ((lat IS NULL OR lat BETWEEN -11.5 AND 6.5) AND (lng IS NULL OR lng BETWEEN 94.5 AND 141.5));
  ALTER TABLE "stores" ADD CONSTRAINT "stores_active_has_address_and_pin" CHECK (active IS NOT TRUE OR (lat IS NOT NULL AND lng IS NOT NULL AND address IS NOT NULL AND btrim(address) <> ''));
  DROP TYPE "public"."enum_works_cataloguing_ai_draft";
  DROP TYPE "public"."enum__works_v_version_cataloguing_ai_draft";
  DROP TYPE "public"."enum_sources_status";
  DROP TYPE "public"."enum__sources_v_version_status";
  DROP TYPE "public"."enum__sources_v_published_locale";`)
  // Hand-written, step 1: UPDATE, DELETE and TRUNCATE of payment_events fail for any session
  // (collections/payment-events/append-only.ts PAYMENT_EVENTS_APPEND_ONLY_SQL, verbatim).
  await db.execute(sql.raw(PAYMENT_EVENTS_APPEND_ONLY_SQL))
  // Hand-written, step 2: the order number's sequence (COMMERCE.md §8).
  await db.execute(sql.raw(ORDERS_NUMBER_SEQUENCE_SQL))
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  // Hand-written: the two steps above, undone before their tables go.
  await db.execute(sql.raw(ORDERS_NUMBER_SEQUENCE_DOWN_SQL))
  await db.execute(sql.raw(PAYMENT_EVENTS_APPEND_ONLY_DOWN_SQL))
  await db.execute(sql`
   CREATE TYPE "public"."enum_works_cataloguing_ai_draft" AS ENUM('title', 'originalTitle', 'publication', 'date', 'makers', 'places', 'subjects', 'technique', 'colour', 'condition', 'references', 'seo');
  CREATE TYPE "public"."enum__works_v_version_cataloguing_ai_draft" AS ENUM('title', 'originalTitle', 'publication', 'date', 'makers', 'places', 'subjects', 'technique', 'colour', 'condition', 'references', 'seo');
  CREATE TYPE "public"."enum_sources_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__sources_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__sources_v_published_locale" AS ENUM('en', 'id');
  CREATE TABLE "works_cataloguing_ai_draft" (
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"value" "enum_works_cataloguing_ai_draft",
  	"id" serial PRIMARY KEY NOT NULL
  );
  
  CREATE TABLE "_works_v_version_cataloguing_ai_draft" (
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"value" "enum__works_v_version_cataloguing_ai_draft",
  	"id" serial PRIMARY KEY NOT NULL
  );
  
  CREATE TABLE "sources" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"short_cite" varchar,
  	"slug" varchar,
  	"citation" varchar,
  	"year" numeric,
  	"url" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "enum_sources_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "_sources_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"parent_id" integer,
  	"version_short_cite" varchar,
  	"version_slug" varchar,
  	"version_citation" varchar,
  	"version_year" numeric,
  	"version_url" varchar,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "enum__sources_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"snapshot" boolean,
  	"published_locale" "enum__sources_v_published_locale",
  	"latest" boolean
  );
  
  ALTER TABLE "users_access_changes" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "stores_images" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "stores_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "stock_levels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orders_lines" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orders_history" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orders_payment_attempts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orders" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payment_events" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "discounts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "products_images" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "products_images_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "products_variants" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "products_variants_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "products" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "products_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_products_v_version_images" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_products_v_version_images_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_products_v_version_variants" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_products_v_version_variants_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_products_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_products_v_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "redirects" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "leads_status_history" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "leads" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "leads_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "partners" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "partners_texts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "chat_sessions_transcript" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "chat_sessions" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "chat_sessions_texts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "chat_sessions_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "events" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "site_settings_gallery_social" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "site_settings_shop_social" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "site_settings_shop_delivery_bands" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "site_settings" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "site_settings_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "site_settings_texts" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "users_access_changes" CASCADE;
  DROP TABLE "stores_images" CASCADE;
  DROP TABLE "stores_locales" CASCADE;
  DROP TABLE "stock_levels" CASCADE;
  DROP TABLE "orders_lines" CASCADE;
  DROP TABLE "orders_history" CASCADE;
  DROP TABLE "orders_payment_attempts" CASCADE;
  DROP TABLE "orders" CASCADE;
  DROP TABLE "payment_events" CASCADE;
  DROP TABLE "discounts" CASCADE;
  DROP TABLE "products_images" CASCADE;
  DROP TABLE "products_images_locales" CASCADE;
  DROP TABLE "products_variants" CASCADE;
  DROP TABLE "products_variants_locales" CASCADE;
  DROP TABLE "products" CASCADE;
  DROP TABLE "products_locales" CASCADE;
  DROP TABLE "_products_v_version_images" CASCADE;
  DROP TABLE "_products_v_version_images_locales" CASCADE;
  DROP TABLE "_products_v_version_variants" CASCADE;
  DROP TABLE "_products_v_version_variants_locales" CASCADE;
  DROP TABLE "_products_v" CASCADE;
  DROP TABLE "_products_v_locales" CASCADE;
  DROP TABLE "pages" CASCADE;
  DROP TABLE "pages_locales" CASCADE;
  DROP TABLE "pages_rels" CASCADE;
  DROP TABLE "_pages_v" CASCADE;
  DROP TABLE "_pages_v_locales" CASCADE;
  DROP TABLE "_pages_v_rels" CASCADE;
  DROP TABLE "redirects" CASCADE;
  DROP TABLE "leads_status_history" CASCADE;
  DROP TABLE "leads" CASCADE;
  DROP TABLE "leads_rels" CASCADE;
  DROP TABLE "partners" CASCADE;
  DROP TABLE "partners_texts" CASCADE;
  DROP TABLE "chat_sessions_transcript" CASCADE;
  DROP TABLE "chat_sessions" CASCADE;
  DROP TABLE "chat_sessions_texts" CASCADE;
  DROP TABLE "chat_sessions_rels" CASCADE;
  DROP TABLE "events" CASCADE;
  DROP TABLE "site_settings_gallery_social" CASCADE;
  DROP TABLE "site_settings_shop_social" CASCADE;
  DROP TABLE "site_settings_shop_delivery_bands" CASCADE;
  DROP TABLE "site_settings" CASCADE;
  DROP TABLE "site_settings_locales" CASCADE;
  DROP TABLE "site_settings_texts" CASCADE;
  ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_store_staff_have_a_store";
  ALTER TABLE "stores" DROP CONSTRAINT IF EXISTS "stores_pin_in_indonesia";
  ALTER TABLE "stores" DROP CONSTRAINT IF EXISTS "stores_active_has_address_and_pin";
  ALTER TABLE "works" DROP CONSTRAINT IF EXISTS "works_cataloguing_ai_draft_title_verified_by_id_users_id_fk";
  
  ALTER TABLE "works" DROP CONSTRAINT IF EXISTS "works_cataloguing_ai_draft_description_verified_by_id_users_id_fk";
  
  ALTER TABLE "works" DROP CONSTRAINT IF EXISTS "works_cataloguing_ai_draft_object_type_verified_by_id_users_id_fk";
  
  ALTER TABLE "works" DROP CONSTRAINT IF EXISTS "works_cataloguing_ai_draft_date_verified_by_id_users_id_fk";
  
  ALTER TABLE "works" DROP CONSTRAINT IF EXISTS "works_cataloguing_ai_draft_places_verified_by_id_users_id_fk";
  
  ALTER TABLE "works" DROP CONSTRAINT IF EXISTS "works_cataloguing_ai_draft_subjects_verified_by_id_users_id_fk";
  
  ALTER TABLE "works" DROP CONSTRAINT IF EXISTS "works_cataloguing_ai_draft_dimensions_verified_by_id_users_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT IF EXISTS "_works_v_version_cataloguing_ai_draft_title_verified_by_id_users_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT IF EXISTS "_works_v_version_cataloguing_ai_draft_description_verified_by_id_users_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT IF EXISTS "_works_v_version_cataloguing_ai_draft_object_type_verified_by_id_users_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT IF EXISTS "_works_v_version_cataloguing_ai_draft_date_verified_by_id_users_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT IF EXISTS "_works_v_version_cataloguing_ai_draft_places_verified_by_id_users_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT IF EXISTS "_works_v_version_cataloguing_ai_draft_subjects_verified_by_id_users_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT IF EXISTS "_works_v_version_cataloguing_ai_draft_dimensions_verified_by_id_users_id_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_stock_levels_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_orders_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_payment_events_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_discounts_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_products_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_pages_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_redirects_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_leads_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_partners_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_chat_sessions_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_events_fk";
  
  DROP INDEX IF EXISTS "works_public_id_idx";
  DROP INDEX IF EXISTS "works_status_idx";
  DROP INDEX IF EXISTS "works_cataloguing_ai_draft_title_cataloguing_ai_draft_ti_idx";
  DROP INDEX IF EXISTS "works_cataloguing_ai_draft_description_cataloguing_ai_dr_idx";
  DROP INDEX IF EXISTS "works_cataloguing_ai_draft_object_type_cataloguing_ai_dr_idx";
  DROP INDEX IF EXISTS "works_cataloguing_ai_draft_date_cataloguing_ai_draft_dat_idx";
  DROP INDEX IF EXISTS "works_cataloguing_ai_draft_places_cataloguing_ai_draft_p_idx";
  DROP INDEX IF EXISTS "works_cataloguing_ai_draft_subjects_cataloguing_ai_draft_idx";
  DROP INDEX IF EXISTS "works_cataloguing_ai_draft_dimensions_cataloguing_ai_dra_idx";
  DROP INDEX IF EXISTS "_works_v_version_version_public_id_idx";
  DROP INDEX IF EXISTS "_works_v_version_version_status_idx";
  DROP INDEX IF EXISTS "_works_v_version_cataloguing_ai_draft_title_version_cata_idx";
  DROP INDEX IF EXISTS "_works_v_version_cataloguing_ai_draft_description_versio_idx";
  DROP INDEX IF EXISTS "_works_v_version_cataloguing_ai_draft_object_type_versio_idx";
  DROP INDEX IF EXISTS "_works_v_version_cataloguing_ai_draft_date_version_catal_idx";
  DROP INDEX IF EXISTS "_works_v_version_cataloguing_ai_draft_places_version_cat_idx";
  DROP INDEX IF EXISTS "_works_v_version_cataloguing_ai_draft_subjects_version_c_idx";
  DROP INDEX IF EXISTS "_works_v_version_cataloguing_ai_draft_dimensions_version_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_stock_levels_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_orders_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_payment_events_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_discounts_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_products_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_pages_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_redirects_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_leads_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_partners_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_chat_sessions_id_idx";
  DROP INDEX IF EXISTS "payload_locked_documents_rels_events_id_idx";
  ALTER TABLE "works_references" ADD COLUMN "source_id" integer;
  ALTER TABLE "works_references" ADD COLUMN "ref" varchar;
  ALTER TABLE "_works_v_version_references" ADD COLUMN "source_id" integer;
  ALTER TABLE "_works_v_version_references" ADD COLUMN "ref" varchar;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "sources_id" integer;
  ALTER TABLE "works_cataloguing_ai_draft" ADD CONSTRAINT "works_cataloguing_ai_draft_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."works"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_works_v_version_cataloguing_ai_draft" ADD CONSTRAINT "_works_v_version_cataloguing_ai_draft_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."_works_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_sources_v" ADD CONSTRAINT "_sources_v_parent_id_sources_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."sources"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "works_cataloguing_ai_draft_order_idx" ON "works_cataloguing_ai_draft" USING btree ("order");
  CREATE INDEX "works_cataloguing_ai_draft_parent_idx" ON "works_cataloguing_ai_draft" USING btree ("parent_id");
  CREATE INDEX "_works_v_version_cataloguing_ai_draft_order_idx" ON "_works_v_version_cataloguing_ai_draft" USING btree ("order");
  CREATE INDEX "_works_v_version_cataloguing_ai_draft_parent_idx" ON "_works_v_version_cataloguing_ai_draft" USING btree ("parent_id");
  CREATE INDEX "sources_short_cite_idx" ON "sources" USING btree ("short_cite");
  CREATE UNIQUE INDEX "sources_slug_idx" ON "sources" USING btree ("slug");
  CREATE INDEX "sources_updated_at_idx" ON "sources" USING btree ("updated_at");
  CREATE INDEX "sources_created_at_idx" ON "sources" USING btree ("created_at");
  CREATE INDEX "sources__status_idx" ON "sources" USING btree ("_status");
  CREATE INDEX "_sources_v_parent_idx" ON "_sources_v" USING btree ("parent_id");
  CREATE INDEX "_sources_v_version_version_short_cite_idx" ON "_sources_v" USING btree ("version_short_cite");
  CREATE INDEX "_sources_v_version_version_slug_idx" ON "_sources_v" USING btree ("version_slug");
  CREATE INDEX "_sources_v_version_version_updated_at_idx" ON "_sources_v" USING btree ("version_updated_at");
  CREATE INDEX "_sources_v_version_version_created_at_idx" ON "_sources_v" USING btree ("version_created_at");
  CREATE INDEX "_sources_v_version_version__status_idx" ON "_sources_v" USING btree ("version__status");
  CREATE INDEX "_sources_v_created_at_idx" ON "_sources_v" USING btree ("created_at");
  CREATE INDEX "_sources_v_updated_at_idx" ON "_sources_v" USING btree ("updated_at");
  CREATE INDEX "_sources_v_snapshot_idx" ON "_sources_v" USING btree ("snapshot");
  CREATE INDEX "_sources_v_published_locale_idx" ON "_sources_v" USING btree ("published_locale");
  CREATE INDEX "_sources_v_latest_idx" ON "_sources_v" USING btree ("latest");
  ALTER TABLE "works_references" ADD CONSTRAINT "works_references_source_id_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."sources"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v_version_references" ADD CONSTRAINT "_works_v_version_references_source_id_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."sources"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_sources_fk" FOREIGN KEY ("sources_id") REFERENCES "public"."sources"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "works_references_source_idx" ON "works_references" USING btree ("source_id");
  CREATE INDEX "_works_v_version_references_source_idx" ON "_works_v_version_references" USING btree ("source_id");
  CREATE INDEX "payload_locked_documents_rels_sources_id_idx" ON "payload_locked_documents_rels" USING btree ("sources_id");
  ALTER TABLE "stores" DROP COLUMN "area";
  ALTER TABLE "stores" DROP COLUMN "address";
  ALTER TABLE "stores" DROP COLUMN "lat";
  ALTER TABLE "stores" DROP COLUMN "lng";
  ALTER TABLE "stores" DROP COLUMN "whatsapp";
  ALTER TABLE "stores" DROP COLUMN "active";
  ALTER TABLE "stores" DROP COLUMN "listed";
  ALTER TABLE "stores" DROP COLUMN "notes";
  ALTER TABLE "works_references" DROP COLUMN "citation";
  ALTER TABLE "works" DROP COLUMN "public_id";
  ALTER TABLE "works" DROP COLUMN "status";
  ALTER TABLE "works" DROP COLUMN "location";
  ALTER TABLE "works" DROP COLUMN "asking_price";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_title_drafted";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_title_verified_by_id";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_title_verified_at";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_description_drafted";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_description_verified_by_id";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_description_verified_at";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_object_type_drafted";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_object_type_verified_by_id";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_object_type_verified_at";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_date_drafted";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_date_verified_by_id";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_date_verified_at";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_places_drafted";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_places_verified_by_id";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_places_verified_at";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_subjects_drafted";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_subjects_verified_by_id";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_subjects_verified_at";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_dimensions_drafted";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_dimensions_verified_by_id";
  ALTER TABLE "works" DROP COLUMN "cataloguing_ai_draft_dimensions_verified_at";
  ALTER TABLE "_works_v_version_references" DROP COLUMN "citation";
  ALTER TABLE "_works_v" DROP COLUMN "version_public_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_status";
  ALTER TABLE "_works_v" DROP COLUMN "version_location";
  ALTER TABLE "_works_v" DROP COLUMN "version_asking_price";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_title_drafted";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_title_verified_by_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_title_verified_at";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_description_drafted";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_description_verified_by_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_description_verified_at";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_object_type_drafted";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_object_type_verified_by_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_object_type_verified_at";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_date_drafted";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_date_verified_by_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_date_verified_at";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_places_drafted";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_places_verified_by_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_places_verified_at";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_subjects_drafted";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_subjects_verified_by_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_subjects_verified_at";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_dimensions_drafted";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_dimensions_verified_by_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_cataloguing_ai_draft_dimensions_verified_at";
  ALTER TABLE "media" DROP COLUMN "subject";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "stock_levels_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "orders_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "payment_events_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "discounts_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "products_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "pages_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "redirects_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "leads_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "partners_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "chat_sessions_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "events_id";
  DROP TYPE "public"."enum_users_access_changes_from_role";
  DROP TYPE "public"."enum_users_access_changes_to_role";
  DROP TYPE "public"."enum_orders_history_from";
  DROP TYPE "public"."enum_orders_history_to";
  DROP TYPE "public"."enum_orders_history_actor";
  DROP TYPE "public"."enum_orders_site";
  DROP TYPE "public"."enum_orders_channel";
  DROP TYPE "public"."enum_orders_contact_locale";
  DROP TYPE "public"."enum_orders_discount_kind";
  DROP TYPE "public"."enum_orders_status";
  DROP TYPE "public"."enum_payment_events_provider";
  DROP TYPE "public"."enum_payment_events_source";
  DROP TYPE "public"."enum_discounts_kind";
  DROP TYPE "public"."enum_products_site";
  DROP TYPE "public"."enum_products_status";
  DROP TYPE "public"."enum_products_translation_status";
  DROP TYPE "public"."enum__products_v_version_site";
  DROP TYPE "public"."enum__products_v_version_status";
  DROP TYPE "public"."enum__products_v_published_locale";
  DROP TYPE "public"."enum__products_v_version_translation_status";
  DROP TYPE "public"."work_status_vocabulary";
  DROP TYPE "public"."enum_works_location";
  DROP TYPE "public"."enum__works_v_version_location";
  DROP TYPE "public"."enum_media_subject";
  DROP TYPE "public"."enum_pages_site";
  DROP TYPE "public"."enum_pages_kind";
  DROP TYPE "public"."enum_pages_status";
  DROP TYPE "public"."enum__pages_v_version_site";
  DROP TYPE "public"."enum__pages_v_version_kind";
  DROP TYPE "public"."enum__pages_v_version_status";
  DROP TYPE "public"."enum__pages_v_published_locale";
  DROP TYPE "public"."enum_redirects_site";
  DROP TYPE "public"."enum_redirects_code";
  DROP TYPE "public"."enum_redirects_source";
  DROP TYPE "public"."enum_leads_status_history_status";
  DROP TYPE "public"."enum_leads_kind";
  DROP TYPE "public"."enum_leads_site";
  DROP TYPE "public"."enum_leads_source";
  DROP TYPE "public"."enum_leads_payload_preferred_channel";
  DROP TYPE "public"."enum_leads_payload_locale";
  DROP TYPE "public"."enum_leads_status";
  DROP TYPE "public"."enum_partners_kind";
  DROP TYPE "public"."enum_partners_site";
  DROP TYPE "public"."enum_partners_status";
  DROP TYPE "public"."enum_chat_sessions_transcript_role";
  DROP TYPE "public"."enum_chat_sessions_site";
  DROP TYPE "public"."enum_chat_sessions_locale";
  DROP TYPE "public"."enum_chat_sessions_outcome";
  DROP TYPE "public"."enum_events_site";
  DROP TYPE "public"."enum_events_name";
  DROP TYPE "public"."enum_events_source";
  DROP TYPE "public"."enum_events_device_class";
  DROP TYPE "public"."enum_events_locale";`)
}

/** Hand-written step 1: `collections/payment-events/append-only.ts`, as of this migration. */
export const PAYMENT_EVENTS_APPEND_ONLY_SQL = `
CREATE OR REPLACE FUNCTION payment_events_append_only() RETURNS trigger
  LANGUAGE plpgsql
  SET search_path = pg_catalog, public
AS $$
BEGIN
  RAISE EXCEPTION 'payment_events is append-only: % refused', TG_OP
    USING ERRCODE = 'restrict_violation',
          HINT = 'A payment event records what the payment provider said; insert a new one instead.';
END;
$$;

CREATE TRIGGER payment_events_no_update_or_delete
  BEFORE UPDATE OR DELETE ON payment_events
  FOR EACH ROW EXECUTE FUNCTION payment_events_append_only();

CREATE TRIGGER payment_events_no_truncate
  BEFORE TRUNCATE ON payment_events
  FOR EACH STATEMENT EXECUTE FUNCTION payment_events_append_only();
`

export const PAYMENT_EVENTS_APPEND_ONLY_DOWN_SQL = `
DROP TRIGGER IF EXISTS payment_events_no_truncate ON payment_events;
DROP TRIGGER IF EXISTS payment_events_no_update_or_delete ON payment_events;
DROP FUNCTION IF EXISTS payment_events_append_only();
`

/** Hand-written step 2: the order number's sequence (COMMERCE.md §8). */
export const ORDERS_NUMBER_SEQUENCE_SQL = `
CREATE SEQUENCE IF NOT EXISTS orders_number_seq AS bigint START WITH 100001 OWNED BY orders.number;
`

export const ORDERS_NUMBER_SEQUENCE_DOWN_SQL = `
DROP SEQUENCE IF EXISTS orders_number_seq;
`
